import { FormEvent, useContext, useEffect, useRef, useState } from "react";
import { api, Propriedade } from "../../api/propriedades";
import { Modulo } from "../../api/usuarios";
import { AcoesContext, autorizado, DestinoConsulta } from "../../components/AcoesContext";
import StatusBackup from "../../components/StatusBackup";
import { nomeModulo } from "../../components/gruposModulos";
type Alerta = { id: string; tipo: string; titulo: string; modulo: Modulo; registro_id?: number; filtros: Record<string, string>; nivel: string };
type Saldo = { propriedade_id: number; propriedade: string; cultura: string; safra: string; fisico_kg: string; disponivel_kg: string };
type Painel = { gerado_em: string; resumo: Record<string, string | number>; alertas: Alerta[]; saldos: Saldo[]; limite_saldos: number; limite_por_tipo: number };
const INDICADORES: Record<string, [string, "kg" | "moeda" | "numero"]> = { saldo_terceiros_kg: ["Estoque de terceiros", "kg"], estoque_total_kg: ["Estoque físico armazenado (próprio + terceiros)", "kg"], propriedades: ["Propriedades", "numero"], cargas: ["Cargas recebidas", "numero"], producao_kg: ["Produção líquida", "kg"], saldo_fisico_kg: ["Saldo físico", "kg"], saldo_disponivel_kg: ["Saldo disponível", "kg"], vendas_kg: ["Vendas registradas", "kg"], entregas_kg: ["Entregas líquidas", "kg"], a_pagar: ["A pagar", "moeda"], a_receber: ["A receber", "moeda"], contas_7_dias: ["Contas nos próximos 7 dias", "numero"], estoque_baixo: ["Produtos abaixo do mínimo", "numero"] };
const numero = (valor: string | number) => Number(valor).toLocaleString("pt-BR", {maximumFractionDigits: 3});
export default function PainelPage({ propriedades, abrir }: { propriedades: Propriedade[]; abrir: (destino: Omit<DestinoConsulta, "chave">) => void }) {
  const contexto=useContext(AcoesContext);const administrador=contexto?.acesso?.is_staff===true;
  const secoes:Record<string,string>={propriedades:"estrutura",cargas:"produtividade",producao_kg:"producao_propriedade",saldo_fisico_kg:"saldos",saldo_disponivel_kg:"saldos",estoque_total_kg:"saldos",vendas_kg:"vendas",entregas_kg:"entregas",a_pagar:"financeiro",a_receber:"financeiro",contas_7_dias:"financeiro",estoque_baixo:"estoque_insumos"};
  const [dados, setDados] = useState<Painel | null>(null); const [filtros, setFiltros] = useState({propriedade: "", safra: ""}); const [aplicados, setAplicados] = useState(filtros);
  const [tipo, setTipo] = useState(""); const [erro, setErro] = useState(""); const [carregando, setCarregando] = useState(true); const ultima = useRef(0); const [quantidade, setQuantidade] = useState(10);
  async function carregar(selecao = filtros) { const id = ++ultima.current; setCarregando(true); setErro("");
    try { const {data} = await api.get<Painel>("/core/painel/", {params: selecao}); if (id !== ultima.current) return; setDados(data); setAplicados(selecao); }
    catch { if (id === ultima.current) setErro("Não foi possível carregar o painel. Tente atualizar."); } finally { if (id === ultima.current) setCarregando(false); }
  }
  useEffect(() => { void carregar({propriedade: "", safra: ""}); return () => { ultima.current++; }; }, []);
  const alertas = dados?.alertas.filter(item => !tipo || item.tipo === tipo) ?? [];
  return <section className="modulo-painel"><div className="card painel-apresentacao"><h2>Visão geral da gestão</h2><p>Produção, saldos e compromissos dos setores que você pode consultar.</p>
    <form className="painel-filtros nao-imprimir" onSubmit={(e: FormEvent) => { e.preventDefault(); void carregar(); }}><label>Propriedade<select value={filtros.propriedade} onChange={e => setFiltros({...filtros, propriedade: e.target.value})}><option value="">Todas</option>{propriedades.map(item => <option key={item.id} value={item.id}>{item.nome}</option>)}</select></label><label>Safra<input placeholder="Ex.: 2026/2027" maxLength={20} value={filtros.safra} onChange={e => setFiltros({...filtros, safra: e.target.value})} /></label><button disabled={carregando}>{carregando ? "Atualizando..." : "Atualizar painel"}</button></form>
    {dados && <small>Consulta: {propriedades.find(item => String(item.id) === aplicados.propriedade)?.nome || "Todas as propriedades"} · {aplicados.safra || "Todas as safras"} · Atualizado em {new Date(dados.gerado_em).toLocaleString("pt-BR")}</small>}
  </div>{erro && <p role="alert" className="erro card">{erro}</p>}{carregando && <p role="status">Carregando indicadores...</p>}
  {dados && <><section className="painel-indicadores" aria-label="Indicadores da consulta">{Object.entries(dados.resumo).filter(([chave]) => INDICADORES[chave]).map(([chave, valor]) => { const [rotulo, unidade] = INDICADORES[chave]; return <article className="card" key={chave}><span>{rotulo}</span><strong className={Number(valor) < 0 ? "valor-negativo" : ""}>{unidade === "moeda" ? Number(valor).toLocaleString("pt-BR", {style:"currency", currency:"BRL"}) : `${numero(valor)}${unidade === "kg" ? " kg" : ""}`}</strong>{secoes[chave]&&(contexto===null||autorizado(contexto.acesso,"relatorios","consultar"))&&<button className="secundario nao-imprimir" type="button" aria-label={`Ver registros: ${rotulo}`} onClick={()=>abrir({modulo:"relatorios",filtros:{...aplicados,secao:secoes[chave]}})}>Ver registros</button>}</article>; })}</section>
  {!Object.keys(dados.resumo).length && <p className="card">Nenhum setor disponível para sua conta. Solicite acesso ao administrador.</p>}
  <section className="card painel-alertas"><div className="painel-titulo"><div><h2>Pontos para conferir</h2><p>Os avisos ajudam na revisão dos registros. Sobra técnica e lançamentos semelhantes podem ser legítimos.</p></div><label className="nao-imprimir">Tipo de aviso<select value={tipo} onChange={e => {setTipo(e.target.value); setQuantidade(10);}}><option value="">Todos ({dados.alertas.length})</option>{[...new Set(dados.alertas.map(item => item.tipo))].map(item => <option key={item} value={item}>{item.replace(/-/g, " ")}</option>)}</select></label></div>
    {!alertas.length ? <p>Nenhum aviso encontrado nesta consulta.</p> : <ul className="painel-lista-alertas">{alertas.slice(0, quantidade).map(item => <li key={item.id} className={item.nivel === "urgente" ? "aviso-urgente" : ""}><div><span className="kicker">{nomeModulo(item.modulo)} · {item.tipo.replace(/-/g, " ")}</span><p>{item.titulo}</p></div><button type="button" className="secundario" onClick={() => abrir({modulo:item.modulo, filtros:item.filtros, registro:item.registro_id})}>Conferir</button></li>)}</ul>}
    {alertas.length > quantidade && <button type="button" className="secundario" onClick={() => setQuantidade(atual => atual + 10)}>Mostrar mais avisos ({alertas.length - quantidade})</button>}<small>A consulta apresenta até {dados.limite_por_tipo} avisos por tipo. Abra o setor para conferir todos os registros.</small>
  </section>{dados.saldos.length > 0 && <section className="card"><h2>Saldos por propriedade</h2><div className="tabela-responsiva"><table><thead><tr><th>Propriedade</th><th>Cultura / safra</th><th>Físico</th><th>Disponível</th><th className="nao-imprimir">Ações</th></tr></thead><tbody>{dados.saldos.map((item, indice) => <tr key={indice}><td>{item.propriedade}</td><td>{item.cultura} · {item.safra}</td><td>{numero(item.fisico_kg)} kg</td><td className={Number(item.disponivel_kg) < 0 ? "valor-negativo" : ""}>{numero(item.disponivel_kg)} kg</td><td className="nao-imprimir"><button type="button" className="secundario" onClick={() => abrir({modulo:"producao-saldos", filtros:{propriedade:String(item.propriedade_id || ""), cultura:item.cultura, safra:item.safra}})}>Ver saldo</button></td></tr>)}</tbody></table></div><small>Até {dados.limite_saldos} combinações de propriedade, cultura e safra.</small></section>}</>}
  {administrador&&<StatusBackup/>}</section>;
}
