# Generated by Django 5.1.15 on 2026-07-26 02:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propriedades', '0003_propriedade_area_calculada_hectares_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('aplicacao', models.CharField(choices=[('despesa', 'Despesa'), ('receita', 'Receita'), ('ambos', 'Ambos')], default='ambos', max_length=10)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='ParceiroFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160)),
                ('tipo', models.CharField(choices=[('fornecedor', 'Fornecedor'), ('cliente', 'Cliente'), ('ambos', 'Ambos')], max_length=12)),
                ('documento', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='CentroCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('safra', models.CharField(blank=True, max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('propriedade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='centros_custo', to='propriedades.propriedade')),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='LancamentoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pagar', 'Conta a pagar'), ('receber', 'Conta a receber')], max_length=10)),
                ('descricao', models.CharField(max_length=220)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('safra', models.CharField(blank=True, max_length=20)),
                ('data_emissao', models.DateField(default=django.utils.timezone.localdate)),
                ('data_vencimento', models.DateField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('liquidado', 'Liquidado'), ('cancelado', 'Cancelado')], default='pendente', max_length=12)),
                ('data_liquidacao', models.DateField(blank=True, null=True)),
                ('valor_liquidado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='financeiro.categoriafinanceira')),
                ('centro_custo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='financeiro.centrocusto')),
                ('propriedade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_financeiros', to='propriedades.propriedade')),
                ('parceiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='financeiro.parceirofinanceiro')),
            ],
            options={
                'ordering': ('data_vencimento', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='centrocusto',
            constraint=models.UniqueConstraint(fields=('nome', 'propriedade', 'safra'), name='financeiro_centro_unico_contexto'),
        ),
        migrations.AddIndex(
            model_name='lancamentofinanceiro',
            index=models.Index(fields=['tipo', 'status', 'data_vencimento'], name='financeiro_tipo_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='lancamentofinanceiro',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='financeiro_valor_positivo'),
        ),
        migrations.AddConstraint(
            model_name='lancamentofinanceiro',
            constraint=models.CheckConstraint(condition=models.Q(('valor_liquidado__isnull', True), ('valor_liquidado__gt', 0), _connector='OR'), name='financeiro_liquidado_positivo'),
        ),
    ]
