# Generated by Django 5.1.15 on 2026-09-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='codigo_barras',
            field=models.CharField(blank=True, default='', max_length=44),
        ),
    ]
