# Generated by Django 5.1.15 on 2026-09-12 15:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_codigo_barras'),
        ('propriedades', '0003_propriedade_area_calculada_hectares_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelamentoFinanceiro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assinatura', models.CharField(max_length=64)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='parcela_numero',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='recebedor_nome',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='financeiro.categoriafinanceira'),
        ),
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='parcelamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parcelas', to='financeiro.parcelamentofinanceiro'),
        ),
        migrations.AddConstraint(
            model_name='lancamentofinanceiro',
            constraint=models.UniqueConstraint(fields=('parcelamento', 'parcela_numero'), name='financeiro_parcela_unica'),
        ),
    ]
