# Generated by Django 5.1.15 on 2026-09-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_parcelamentofinanceiro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='total_boletos',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
