# Generated by Django 5.1.15 on 2026-07-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propriedades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriedade',
            name='arquivo_kml',
            field=models.FileField(blank=True, null=True, upload_to='kml/'),
        ),
        migrations.AddField(
            model_name='propriedade',
            name='proprietario',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='propriedade',
            name='uf',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
