# Generated by Django 5.1.15 on 2026-07-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propriedades', '0002_propriedade_arquivo_kml_propriedade_proprietario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriedade',
            name='area_calculada_hectares',
            field=models.DecimalField(blank=True, decimal_places=4, editable=False, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='propriedade',
            name='geometria_geojson',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
    ]
