# Generated by Django 5.1.15 on 2026-10-01 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propriedades', '0003_propriedade_area_calculada_hectares_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriedade',
            name='bp_cvale',
            field=models.CharField(blank=True, default='', help_text='BP/BEP da propriedade, utilizado exclusivamente no faturamento C.Vale.', max_length=40, validators=[django.core.validators.RegexValidator('^[0-9]*\\Z', 'Informe somente números no BP da C.Vale.')]),
        ),
    ]
