# Generated by Django 5.1.15 on 2026-07-26 03:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0001_initial'),
        ('talhoes', '0007_talhao_area_calculada_hectares'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacaoAgricola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('preparo', 'Preparo do solo'), ('plantio', 'Plantio'), ('adubacao', 'Adubação'), ('pulverizacao', 'Pulverização'), ('irrigacao', 'Irrigação'), ('colheita', 'Colheita'), ('outra', 'Outra')], max_length=20)),
                ('descricao', models.CharField(max_length=220)),
                ('data_planejada', models.DateField()),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planejada', 'Planejada'), ('em_execucao', 'Em execução'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='planejada', max_length=15)),
                ('area_hectares', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('responsavel', models.CharField(blank=True, max_length=120)),
                ('custo_estimado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('custo_realizado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operacoes_agricolas', to=settings.AUTH_USER_MODEL)),
                ('talhao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operacoes', to='talhoes.talhao')),
            ],
            options={
                'ordering': ('data_planejada', 'id'),
            },
        ),
        migrations.CreateModel(
            name='InsumoOperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_planejada', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('quantidade_utilizada', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos_em_operacoes', to='estoque.loteestoque')),
                ('movimentacao_estoque', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='insumo_operacao', to='estoque.movimentacaoestoque')),
                ('operacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='producao.operacaoagricola')),
            ],
            options={
                'ordering': ('lote__produto__nome', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='operacaoagricola',
            index=models.Index(fields=['status', 'data_planejada'], name='producao_status_data_idx'),
        ),
        migrations.AddConstraint(
            model_name='operacaoagricola',
            constraint=models.CheckConstraint(condition=models.Q(('area_hectares__gt', 0)), name='producao_operacao_area_positiva'),
        ),
        migrations.AddConstraint(
            model_name='operacaoagricola',
            constraint=models.CheckConstraint(condition=models.Q(('custo_estimado__gte', 0)), name='producao_custo_estimado_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='operacaoagricola',
            constraint=models.CheckConstraint(condition=models.Q(('custo_realizado__isnull', True), ('custo_realizado__gte', 0), _connector='OR'), name='producao_custo_realizado_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='insumooperacao',
            constraint=models.UniqueConstraint(fields=('operacao', 'lote'), name='producao_operacao_lote_unico'),
        ),
    ]
