# Generated manually for the integrated agricultural production domain.

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("estoque", "0001_initial"),
        ("financeiro", "0001_initial"),
        ("producao", "0001_initial"),
        ("propriedades", "0004_acessopropriedade"),
        ("talhoes", "0007_talhao_area_calculada_hectares"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cultura",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=80, unique=True)),
                ("codigo", models.SlugField(max_length=40, unique=True)),
                ("peso_saca_kg", models.DecimalField(decimal_places=3, default=Decimal("60"), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal("0.001"))])),
                ("ativa", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ("nome",)},
        ),
        migrations.CreateModel(
            name="Safra",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=30, unique=True)),
                ("data_inicio", models.DateField(blank=True, null=True)),
                ("data_fim", models.DateField(blank=True, null=True)),
                ("ativa", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ("-nome",)},
        ),
        migrations.CreateModel(
            name="Motorista",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=160)),
                ("documento", models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ("telefone", models.CharField(blank=True, max_length=30)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("terceiro", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="motoristas_producao", to="financeiro.parceirofinanceiro")),
            ],
            options={"ordering": ("nome",)},
        ),
        migrations.CreateModel(
            name="CadPro",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("codigo", models.CharField(max_length=80)),
                ("titular", models.CharField(max_length=160)),
                ("documento", models.CharField(blank=True, max_length=20)),
                ("inscricao_estadual", models.CharField(blank=True, max_length=30)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("propriedade", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="cadpros", to="propriedades.propriedade")),
            ],
            options={"ordering": ("propriedade__nome", "codigo")},
        ),
        migrations.AddConstraint(
            model_name="cadpro",
            constraint=models.UniqueConstraint(fields=("propriedade", "codigo"), name="producao_cadpro_codigo_propriedade_unico"),
        ),
        migrations.CreateModel(
            name="Veiculo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("placa", models.CharField(max_length=10, unique=True)),
                ("tipo", models.CharField(choices=[("caminhao", "Caminhão"), ("carreta", "Carreta"), ("outro", "Outro")], default="caminhao", max_length=12)),
                ("descricao", models.CharField(blank=True, max_length=120)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("motorista_padrao", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="veiculos", to="producao.motorista")),
                ("terceiro", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="veiculos_producao", to="financeiro.parceirofinanceiro")),
            ],
            options={"ordering": ("placa",)},
        ),
        migrations.CreateModel(
            name="AcessoCadPro",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("cadpro", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="acessos", to="producao.cadpro")),
                ("usuario", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="acessos_cadpro", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("cadpro__propriedade__nome", "cadpro__codigo", "usuario__username")},
        ),
        migrations.AddConstraint(
            model_name="acessocadpro",
            constraint=models.UniqueConstraint(fields=("cadpro", "usuario"), name="producao_cadpro_usuario_unico"),
        ),
        migrations.AddIndex(
            model_name="acessocadpro",
            index=models.Index(fields=["usuario", "ativo"], name="producao_cadpro_usuario_idx"),
        ),
        migrations.CreateModel(
            name="ContratoProducao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("numero", models.CharField(max_length=80)),
                ("data_contrato", models.DateField(default=django.utils.timezone.localdate)),
                ("data_limite", models.DateField(blank=True, null=True)),
                ("quantidade_kg", models.DecimalField(decimal_places=3, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal("0.001"))])),
                ("preco_saca", models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal("0.0001"))])),
                ("tolerancia_percentual", models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal("0")), django.core.validators.MaxValueValidator(Decimal("100"))])),
                ("status", models.CharField(choices=[("aberto", "Aberto"), ("concluido", "Concluído"), ("cancelado", "Cancelado")], default="aberto", max_length=12)),
                ("observacoes", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("cadpro", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="contratos", to="producao.cadpro")),
                ("comprador", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="contratos_producao", to="financeiro.parceirofinanceiro")),
                ("cultura", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="contratos", to="producao.cultura")),
                ("propriedade", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="contratos_producao", to="propriedades.propriedade")),
                ("safra", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="contratos", to="producao.safra")),
            ],
            options={"ordering": ("-data_contrato", "numero")},
        ),
        migrations.AddConstraint(
            model_name="contratoproducao",
            constraint=models.UniqueConstraint(fields=("comprador", "numero"), name="producao_contrato_comprador_numero_unico"),
        ),
        migrations.CreateModel(
            name="MovimentacaoGraos",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tipo", models.CharField(choices=[("entrada", "Entrada"), ("saida", "Saída"), ("transferencia", "Transferência"), ("ajuste_entrada", "Ajuste de entrada"), ("ajuste_saida", "Ajuste de saída"), ("estorno", "Estorno")], max_length=18)),
                ("quantidade_kg", models.DecimalField(decimal_places=3, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal("0.001"))])),
                ("referencia_tipo", models.CharField(blank=True, max_length=40)),
                ("referencia_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("motivo", models.CharField(blank=True, max_length=240)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("cadpro", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="movimentacoes", to="producao.cadpro")),
                ("criado_por", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="movimentacoes_graos", to=settings.AUTH_USER_MODEL)),
                ("cultura", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="movimentacoes", to="producao.cultura")),
                ("estorno_de", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="estorno", to="producao.movimentacaograos")),
                ("local_destino", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="entradas_graos", to="estoque.localestoque")),
                ("local_origem", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="saidas_graos", to="estoque.localestoque")),
                ("propriedade", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="movimentacoes_graos", to="propriedades.propriedade")),
                ("safra", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="movimentacoes", to="producao.safra")),
                ("talhao", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="movimentacoes_graos", to="talhoes.talhao")),
            ],
            options={"ordering": ("-criado_em", "-id")},
        ),
        migrations.AddIndex(
            model_name="movimentacaograos",
            index=models.Index(fields=["propriedade", "safra", "cultura"], name="prod_mov_contexto_idx"),
        ),
        migrations.AddIndex(
            model_name="movimentacaograos",
            index=models.Index(fields=["tipo", "criado_em"], name="prod_mov_tipo_data_idx"),
        ),
        migrations.CreateModel(
            name="RecebimentoProducao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("data", models.DateTimeField(default=django.utils.timezone.now)),
                ("placa_informada", models.CharField(blank=True, max_length=20)),
                ("romaneio", models.CharField(blank=True, max_length=80)),
                ("peso_bruto_kg", models.DecimalField(decimal_places=3, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal("0.001"))])),
                ("tara_kg", models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal("0"))])),
                ("peso_liquido_kg", models.DecimalField(decimal_places=3, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal("0.001"))])),
                ("quantidade_sacas", models.DecimalField(decimal_places=3, default=Decimal("0"), editable=False, max_digits=16)),
                ("umidade_percentual", models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal("0")), django.core.validators.MaxValueValidator(Decimal("100"))])),
                ("impureza_percentual", models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal("0")), django.core.validators.MaxValueValidator(Decimal("100"))])),
                ("defeitos_percentual", models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal("0")), django.core.validators.MaxValueValidator(Decimal("100"))])),
                ("status", models.CharField(choices=[("rascunho", "Rascunho"), ("confirmado", "Confirmado"), ("estornado", "Estornado")], default="rascunho", max_length=12)),
                ("observacoes", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("cadpro", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="recebimentos", to="producao.cadpro")),
                ("criado_por", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="recebimentos_producao", to=settings.AUTH_USER_MODEL)),
                ("cultura", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="recebimentos", to="producao.cultura")),
                ("local_armazenagem", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="recebimentos_producao", to="estoque.localestoque")),
                ("motorista", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="recebimentos", to="producao.motorista")),
                ("movimentacao", models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="recebimento", to="producao.movimentacaograos")),
                ("propriedade", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="recebimentos_producao", to="propriedades.propriedade")),
                ("safra", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="recebimentos", to="producao.safra")),
                ("talhao", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="recebimentos_producao", to="talhoes.talhao")),
                ("veiculo", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="recebimentos", to="producao.veiculo")),
            ],
            options={"ordering": ("-data", "-id")},
        ),
        migrations.AddIndex(
            model_name="recebimentoproducao",
            index=models.Index(fields=["propriedade", "safra", "cultura"], name="prod_receb_contexto_idx"),
        ),
        migrations.AddIndex(
            model_name="recebimentoproducao",
            index=models.Index(fields=["status", "data"], name="prod_receb_status_data_idx"),
        ),
        migrations.CreateModel(
            name="SaldoGraos",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantidade_kg", models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=18)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("cadpro", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="saldos", to="producao.cadpro")),
                ("cultura", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="saldos", to="producao.cultura")),
                ("local_armazenagem", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="saldos_graos", to="estoque.localestoque")),
                ("propriedade", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="saldos_graos", to="propriedades.propriedade")),
                ("safra", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="saldos", to="producao.safra")),
                ("talhao", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="saldos_graos", to="talhoes.talhao")),
            ],
            options={"ordering": ("propriedade__nome", "cadpro__codigo", "cultura__nome", "safra__nome")},
        ),
        migrations.AddConstraint(
            model_name="saldograos",
            constraint=models.CheckConstraint(condition=models.Q(("quantidade_kg__gte", 0)), name="producao_saldo_graos_nao_negativo"),
        ),
        migrations.AddConstraint(
            model_name="saldograos",
            constraint=models.UniqueConstraint(fields=("cadpro", "talhao", "cultura", "safra", "local_armazenagem"), name="producao_saldo_dimensao_unico", nulls_distinct=False),
        ),
        migrations.CreateModel(
            name="EmbarqueProducao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("data", models.DateTimeField(default=django.utils.timezone.now)),
                ("placa_informada", models.CharField(blank=True, max_length=20)),
                ("destino", models.CharField(blank=True, max_length=240)),
                ("romaneio", models.CharField(max_length=80)),
                ("nota_produtor", models.CharField(blank=True, max_length=80)),
                ("nota_empresa", models.CharField(blank=True, max_length=80)),
                ("quantidade_kg", models.DecimalField(decimal_places=3, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal("0.001"))])),
                ("quantidade_sacas", models.DecimalField(decimal_places=3, default=Decimal("0"), editable=False, max_digits=18)),
                ("preco_saca", models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal("0.0001"))])),
                ("valor_total", models.DecimalField(decimal_places=2, default=Decimal("0"), editable=False, max_digits=16)),
                ("status", models.CharField(choices=[("rascunho", "Rascunho"), ("confirmado", "Confirmado"), ("estornado", "Estornado")], default="rascunho", max_length=12)),
                ("observacoes", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("cadpro", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="embarques", to="producao.cadpro")),
                ("comprador", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="embarques_producao", to="financeiro.parceirofinanceiro")),
                ("contrato", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="embarques", to="producao.contratoproducao")),
                ("criado_por", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="embarques_producao", to=settings.AUTH_USER_MODEL)),
                ("cultura", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="embarques", to="producao.cultura")),
                ("lancamento_financeiro", models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="embarque_producao", to="financeiro.lancamentofinanceiro")),
                ("local_armazenagem", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="embarques_producao", to="estoque.localestoque")),
                ("motorista", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="embarques", to="producao.motorista")),
                ("movimentacao", models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="embarque", to="producao.movimentacaograos")),
                ("propriedade", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="embarques_producao", to="propriedades.propriedade")),
                ("safra", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="embarques", to="producao.safra")),
                ("veiculo", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="embarques", to="producao.veiculo")),
            ],
            options={"ordering": ("-data", "-id")},
        ),
        migrations.AddConstraint(
            model_name="embarqueproducao",
            constraint=models.UniqueConstraint(fields=("comprador", "romaneio"), name="producao_embarque_romaneio_unico"),
        ),
        migrations.CreateModel(
            name="AuditoriaProducao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("acao", models.CharField(max_length=60)),
                ("entidade", models.CharField(max_length=80)),
                ("entidade_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("dados_anteriores", models.JSONField(blank=True, default=dict)),
                ("dados_novos", models.JSONField(blank=True, default=dict)),
                ("metadados", models.JSONField(blank=True, default=dict)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("propriedade", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="auditorias_producao", to="propriedades.propriedade")),
                ("usuario", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="auditorias_producao", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("-criado_em", "-id")},
        ),
        migrations.AddIndex(
            model_name="auditoriaproducao",
            index=models.Index(fields=["propriedade", "criado_em"], name="prod_audit_prop_data_idx"),
        ),
        migrations.AddIndex(
            model_name="auditoriaproducao",
            index=models.Index(fields=["entidade", "entidade_id"], name="prod_audit_entidade_idx"),
        ),
        migrations.CreateModel(
            name="ImportacaoPlanilha",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tipo", models.CharField(choices=[("recebimentos", "Recebimentos"), ("movimentacoes", "Movimentações"), ("embarques", "Embarques")], max_length=20)),
                ("arquivo", models.FileField(upload_to="importacoes/producao/%Y/%m/")),
                ("nome_original", models.CharField(max_length=255)),
                ("hash_arquivo", models.CharField(db_index=True, max_length=64)),
                ("mapeamento", models.JSONField(blank=True, default=dict)),
                ("previa", models.JSONField(blank=True, default=list)),
                ("inconsistencias", models.JSONField(blank=True, default=list)),
                ("total_linhas", models.PositiveIntegerField(default=0)),
                ("linhas_importadas", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(choices=[("enviada", "Enviada"), ("validada", "Validada"), ("importada", "Importada"), ("erro", "Erro")], default="enviada", max_length=12)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("confirmado_em", models.DateTimeField(blank=True, null=True)),
                ("cadpro", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="importacoes", to="producao.cadpro")),
                ("criado_por", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="importacoes_producao", to=settings.AUTH_USER_MODEL)),
                ("propriedade", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="importacoes_producao", to="propriedades.propriedade")),
            ],
            options={"ordering": ("-criado_em", "-id")},
        ),
        migrations.AddConstraint(
            model_name="importacaoplanilha",
            constraint=models.UniqueConstraint(fields=("criado_por", "hash_arquivo", "tipo"), name="producao_importacao_usuario_hash_tipo_unico"),
        ),
    ]
