from decimal import Decimal

import apps.producao.joint_models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("producao", "0002_gestao_integrada_producao"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoteConjuntoProducao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("codigo", models.CharField(default=apps.producao.joint_models.gerar_codigo_lote_conjunto, editable=False, max_length=32, unique=True)),
                ("descricao", models.CharField(blank=True, max_length=240)),
                ("variedade", models.CharField(blank=True, max_length=120)),
                ("data_inicio_colheita", models.DateField()),
                ("data_final_colheita", models.DateField(blank=True, null=True)),
                ("modo_rateio", models.CharField(choices=[("sem_rateio", "Conjunta sem rateio"), ("area", "Rateio automático pela área"), ("manual", "Rateio manual")], default="sem_rateio", max_length=16)),
                ("area_total_cadastrada_ha", models.DecimalField(decimal_places=4, default=Decimal("0"), editable=False, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal("0"))])),
                ("area_total_colhida_ha", models.DecimalField(decimal_places=4, default=Decimal("0"), editable=False, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal("0"))])),
                ("peso_bruto_total_kg", models.DecimalField(decimal_places=3, default=Decimal("0"), editable=False, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal("0"))])),
                ("tara_total_kg", models.DecimalField(decimal_places=3, default=Decimal("0"), editable=False, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal("0"))])),
                ("peso_liquido_total_kg", models.DecimalField(decimal_places=3, default=Decimal("0"), editable=False, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal("0"))])),
                ("umidade_media", models.DecimalField(decimal_places=3, default=Decimal("0"), editable=False, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal("0")), django.core.validators.MaxValueValidator(Decimal("100"))])),
                ("impureza_media", models.DecimalField(decimal_places=3, default=Decimal("0"), editable=False, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal("0")), django.core.validators.MaxValueValidator(Decimal("100"))])),
                ("defeitos_medios", models.DecimalField(decimal_places=3, default=Decimal("0"), editable=False, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal("0")), django.core.validators.MaxValueValidator(Decimal("100"))])),
                ("observacoes", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("rascunho", "Rascunho"), ("conferencia", "Em conferência"), ("confirmado", "Confirmado"), ("encerrado", "Encerrado"), ("estornado", "Estornado")], default="rascunho", max_length=16)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("confirmado_em", models.DateTimeField(blank=True, null=True)),
                ("encerrado_em", models.DateTimeField(blank=True, null=True)),
                ("estornado_em", models.DateTimeField(blank=True, null=True)),
                ("cadpro_responsavel", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="lotes_conjuntos_responsaveis", to="producao.cadpro")),
                ("confirmado_por", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="lotes_conjuntos_confirmados", to=settings.AUTH_USER_MODEL)),
                ("criado_por", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="lotes_conjuntos_criados", to=settings.AUTH_USER_MODEL)),
                ("cultura", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="lotes_conjuntos", to="producao.cultura")),
                ("local_armazenagem", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="lotes_conjuntos", to="estoque.localestoque")),
                ("safra", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="lotes_conjuntos", to="producao.safra")),
            ],
            options={
                "ordering": ("-data_inicio_colheita", "-id"),
                "indexes": [models.Index(fields=["status", "data_inicio_colheita"], name="prod_lote_conj_status_idx"), models.Index(fields=["cultura", "safra"], name="prod_lote_conj_cult_idx")],
            },
        ),
        migrations.CreateModel(
            name="ParticipanteLoteConjunto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("area_cadastrada_ha", models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal("0.0001"))])),
                ("area_colhida_ha", models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal("0.0001"))])),
                ("percentual_area", models.DecimalField(decimal_places=5, default=Decimal("0"), editable=False, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal("0")), django.core.validators.MaxValueValidator(Decimal("100"))])),
                ("quantidade_rateada_kg", models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal("0"))])),
                ("metodo_rateio", models.CharField(choices=[("nao_rateado", "Não rateado"), ("area", "Estimado por área"), ("manual", "Ajustado manualmente")], default="nao_rateado", max_length=16)),
                ("excesso_area_autorizado", models.BooleanField(default=False)),
                ("justificativa_excesso_area", models.TextField(blank=True)),
                ("justificativa_rateio", models.TextField(blank=True)),
                ("observacoes", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("autorizado_por", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="areas_conjuntas_autorizadas", to=settings.AUTH_USER_MODEL)),
                ("cadpro", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="participacoes_lotes_conjuntos", to="producao.cadpro")),
                ("lote", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="participantes", to="producao.loteconjuntoproducao")),
                ("propriedade", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="participacoes_lotes_conjuntos", to="propriedades.propriedade")),
            ],
            options={
                "ordering": ("propriedade__nome", "id"),
                "indexes": [models.Index(fields=["propriedade", "lote"], name="prod_part_conj_prop_idx")],
                "constraints": [models.UniqueConstraint(fields=("lote", "propriedade"), name="producao_lote_conjunto_propriedade_unica")],
            },
        ),
        migrations.CreateModel(
            name="TalhaoParticipanteLoteConjunto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("area_cadastrada_ha", models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal("0.0001"))])),
                ("area_colhida_ha", models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal("0.0001"))])),
                ("observacoes", models.TextField(blank=True)),
                ("participante", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="talhoes", to="producao.participanteloteconjunto")),
                ("talhao", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="participacoes_lotes_conjuntos", to="talhoes.talhao")),
            ],
            options={
                "ordering": ("talhao__nome", "id"),
                "constraints": [models.UniqueConstraint(fields=("participante", "talhao"), name="producao_lote_conjunto_talhao_unico")],
            },
        ),
        migrations.CreateModel(
            name="CadProLoteConjunto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantidade_atribuida_kg", models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal("0"))])),
                ("metodo_rateio", models.CharField(choices=[("nao_rateado", "Não rateado"), ("area", "Estimado por área"), ("manual", "Ajustado manualmente")], default="nao_rateado", max_length=16)),
                ("justificativa", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("cadpro", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="lotes_conjuntos_participantes", to="producao.cadpro")),
                ("criado_por", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="distribuicoes_cadpro_lote", to=settings.AUTH_USER_MODEL)),
                ("lote", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cadpros_participantes", to="producao.loteconjuntoproducao")),
                ("participante", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="cadpros_distribuidos", to="producao.participanteloteconjunto")),
            ],
            options={
                "ordering": ("cadpro__codigo", "id"),
                "constraints": [models.UniqueConstraint(fields=("lote", "cadpro"), name="producao_lote_conjunto_cadpro_unico")],
            },
        ),
        migrations.CreateModel(
            name="CargaLoteConjunto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("data_hora", models.DateTimeField(default=django.utils.timezone.now)),
                ("placa_cavalo_informada", models.CharField(blank=True, max_length=20)),
                ("placa_carreta_informada", models.CharField(blank=True, max_length=20)),
                ("origem", models.CharField(blank=True, max_length=240)),
                ("destino", models.CharField(blank=True, max_length=240)),
                ("peso_bruto_kg", models.DecimalField(decimal_places=3, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal("0.001"))])),
                ("tara_kg", models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal("0"))])),
                ("peso_liquido_kg", models.DecimalField(decimal_places=3, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal("0.001"))])),
                ("umidade_percentual", models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal("0")), django.core.validators.MaxValueValidator(Decimal("100"))])),
                ("impureza_percentual", models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal("0")), django.core.validators.MaxValueValidator(Decimal("100"))])),
                ("defeitos_percentual", models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal("0")), django.core.validators.MaxValueValidator(Decimal("100"))])),
                ("romaneio", models.CharField(blank=True, max_length=80)),
                ("numero_balanca", models.CharField(blank=True, max_length=80)),
                ("nota_fiscal", models.CharField(blank=True, max_length=80)),
                ("observacoes", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("criado_por", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="cargas_lotes_conjuntos_criadas", to=settings.AUTH_USER_MODEL)),
                ("local_armazenagem", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="cargas_lotes_conjuntos", to="estoque.localestoque")),
                ("lote", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="cargas", to="producao.loteconjuntoproducao")),
                ("motorista", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="cargas_lotes_conjuntos", to="producao.motorista")),
                ("transportadora", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="cargas_lotes_conjuntos", to="financeiro.parceirofinanceiro")),
                ("veiculo_carreta", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="cargas_como_carreta", to="producao.veiculo")),
                ("veiculo_cavalo", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="cargas_como_cavalo", to="producao.veiculo")),
            ],
            options={
                "ordering": ("data_hora", "id"),
                "indexes": [models.Index(fields=["motorista", "data_hora"], name="prod_carga_conj_mot_idx"), models.Index(fields=["veiculo_cavalo", "data_hora"], name="prod_carga_conj_veic_idx")],
                "constraints": [models.UniqueConstraint(condition=models.Q(("romaneio", ""), _negated=True), fields=("lote", "romaneio"), name="producao_carga_lote_romaneio_unico")],
            },
        ),
        migrations.CreateModel(
            name="SaldoLoteConjunto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantidade_kg", models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal("0"))])),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("local_armazenagem", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="saldos_lotes_conjuntos", to="estoque.localestoque")),
                ("lote", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="saldos_conjuntos", to="producao.loteconjuntoproducao")),
            ],
            options={
                "ordering": ("lote__codigo", "local_armazenagem__nome"),
                "constraints": [models.UniqueConstraint(fields=("lote", "local_armazenagem"), name="producao_saldo_lote_conjunto_local_unico"), models.CheckConstraint(condition=models.Q(("quantidade_kg__gte", 0)), name="producao_saldo_lote_conjunto_nao_negativo")],
            },
        ),
        migrations.CreateModel(
            name="MovimentacaoLoteConjunto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tipo", models.CharField(choices=[("entrada", "Entrada"), ("saida", "Saída"), ("transferencia", "Transferência"), ("distribuicao", "Distribuição"), ("ajuste_entrada", "Ajuste de entrada"), ("ajuste_saida", "Ajuste de saída"), ("estorno", "Estorno")], max_length=18)),
                ("quantidade_kg", models.DecimalField(decimal_places=3, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal("0.001"))])),
                ("saldo_origem_anterior", models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ("saldo_origem_posterior", models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ("saldo_destino_anterior", models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ("saldo_destino_posterior", models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ("referencia_tipo", models.CharField(blank=True, max_length=50)),
                ("referencia_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("motivo", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("cadpro", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="movimentacoes_lotes_conjuntos", to="producao.cadpro")),
                ("criado_por", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="movimentacoes_lotes_conjuntos", to=settings.AUTH_USER_MODEL)),
                ("estorno_de", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="movimentacao_estorno", to="producao.movimentacaoloteconjunto")),
                ("local_destino", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="movimentacoes_conjuntas_entrada", to="estoque.localestoque")),
                ("local_origem", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="movimentacoes_conjuntas_saida", to="estoque.localestoque")),
                ("lote", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="movimentacoes_conjuntas", to="producao.loteconjuntoproducao")),
                ("participante", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="movimentacoes", to="producao.participanteloteconjunto")),
            ],
            options={
                "ordering": ("-criado_em", "-id"),
                "indexes": [models.Index(fields=["lote", "tipo", "criado_em"], name="prod_mov_lote_conj_idx")],
            },
        ),
        migrations.CreateModel(
            name="SaidaLoteConjunto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("data_hora", models.DateTimeField(default=django.utils.timezone.now)),
                ("placa_cavalo_informada", models.CharField(blank=True, max_length=20)),
                ("placa_carreta_informada", models.CharField(blank=True, max_length=20)),
                ("destino", models.CharField(blank=True, max_length=240)),
                ("romaneio", models.CharField(max_length=80)),
                ("nota_produtor", models.CharField(blank=True, max_length=80)),
                ("nota_empresa", models.CharField(blank=True, max_length=80)),
                ("quantidade_kg", models.DecimalField(decimal_places=3, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal("0.001"))])),
                ("justificativa", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("rascunho", "Rascunho"), ("confirmada", "Confirmada"), ("estornada", "Estornada")], default="rascunho", max_length=12)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("comprador", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="saidas_lotes_conjuntos", to="financeiro.parceirofinanceiro")),
                ("contrato", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="saidas_lotes_conjuntos", to="producao.contratoproducao")),
                ("criado_por", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="saidas_lotes_conjuntos_criadas", to=settings.AUTH_USER_MODEL)),
                ("local_armazenagem", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="saidas_lotes_conjuntos", to="estoque.localestoque")),
                ("lote", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="saidas_conjuntas", to="producao.loteconjuntoproducao")),
                ("motorista", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="saidas_lotes_conjuntos", to="producao.motorista")),
                ("movimentacao", models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="saida_conjunta", to="producao.movimentacaoloteconjunto")),
                ("veiculo_carreta", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="saidas_conjuntas_como_carreta", to="producao.veiculo")),
                ("veiculo_cavalo", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="saidas_conjuntas_como_cavalo", to="producao.veiculo")),
            ],
            options={
                "ordering": ("-data_hora", "-id"),
                "constraints": [models.UniqueConstraint(fields=("lote", "romaneio"), name="producao_saida_lote_romaneio_unico")],
            },
        ),
    ]
