import { useEffect, useId, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { BotaoAcao } from "./AcoesContext";
import { salvarArquivo } from "../api/arquivos";
export type DadosComprovante={titulo:string;campos:[string,string][]};
export function htmlComprovante(dados:DadosComprovante){const escapar=(v:string)=>v.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'"><title>${escapar(dados.titulo)}</title><style>body{font:16px Arial;color:#183c30;max-width:800px;margin:32px auto;padding:16px}table{width:100%;border-collapse:collapse}th,td{text-align:left;border-bottom:1px solid #ccd8d0;padding:10px;overflow-wrap:anywhere}th{width:35%}@page{size:A4;margin:18mm}</style></head><body><h1>${escapar(dados.titulo)}</h1><p>AGRO-AI-PRO · Resumo para conferência. Não substitui documento fiscal.</p><table>${dados.campos.map(([k,v])=>`<tr><th>${escapar(k)}</th><td>${escapar(v)}</td></tr>`).join("")}</table></body></html>`;}
export default function ComprovanteLancamento({dados,rotulo="Comprovante",tipoDocumento="comprovante"}:{dados:DadosComprovante;rotulo?:string;tipoDocumento?:string}){
  const [aberto,setAberto]=useState(false),dialogo=useRef<HTMLDialogElement>(null),titulo=useId();
  useEffect(()=>{if(aberto)dialogo.current?.showModal();},[aberto]);
  function imprimir(){document.body.classList.add("imprimindo-comprovante");try{window.print();}finally{document.body.classList.remove("imprimindo-comprovante");}}
  return <><BotaoAcao acao="imprimir" className="secundario" type="button" onClick={e=>{e.stopPropagation();setAberto(true);}}>{rotulo}</BotaoAcao>{aberto&&createPortal(<dialog ref={dialogo} className="comprovante-dialogo card" aria-labelledby={titulo} onCancel={e=>{e.preventDefault();setAberto(false);}}><h2 id={titulo}>{dados.titulo}</h2><p>Resumo para conferência. Não substitui documento fiscal.</p><dl>{dados.campos.map(([k,v],i)=><div key={i}><dt>{k}</dt><dd>{v||"—"}</dd></div>)}</dl><div className="acoes nao-imprimir"><button type="button" onClick={imprimir}>Imprimir {tipoDocumento}</button><button type="button" className="secundario" onClick={()=>salvarArquivo(new Blob([htmlComprovante(dados)],{type:"text/html;charset=utf-8"}),`${dados.titulo.replace(/[^a-zA-Z0-9-]/g,"-")}.html`)}>Baixar {tipoDocumento}</button><button autoFocus type="button" className="secundario" onClick={()=>setAberto(false)}>Fechar</button></div></dialog>,document.body)}</>;
}
