import {FormEvent,useState} from 'react';
import {api} from '../api/propriedades';
import {ArmazemGraos} from '../api/cargasColhidas';
import {EntradaTerceiro,TerceiroCadastro} from '../api/terceiros';
import {BotaoAcao} from './AcoesContext';
import {useOperacaoConferida} from './OperacaoConferida';
import {useAlteracoesNaoSalvas} from './AlteracoesNaoSalvas';
import {formatarNumero} from '../utils/numeros';

const rotulos:Record<string,string>={depositante:'Terceiro',terceiro:'Cadastro',peso_bruto_kg:'Peso bruto (kg)',peso_total_kg:'Peso total (kg)',tara_kg:'Tara (kg)',peso_liquido_kg:'Peso líquido (kg)',saldo_kg:'Saldo (kg)',data_entrada:'Data de entrada',armazem_nome:'Armazém',cultura:'Produto',safra:'Safra',placa:'Placa',motorista:'Motorista',documento:'Documento',observacoes:'Observações',umidade_percentual:'Umidade (%)',impureza_percentual:'Impureza (%)',defeitos_percentual:'Avariados (%)',ph:'PH',desconto_total_kg:'Desconto (kg)',desconto_total_percentual:'Desconto (%)'};
export function DadosHistoricos({antes,depois}:{antes?:Record<string,unknown>;depois?:Record<string,unknown>}){
  const campos=Object.keys(rotulos).filter(k=>(antes?.[k]!==undefined||depois?.[k]!==undefined)&&JSON.stringify(antes?.[k])!==JSON.stringify(depois?.[k]));
  return <div className="tabela-scroll"><table><thead><tr><th>Campo</th><th>Original</th><th>Após correção</th></tr></thead><tbody>{campos.map(k=><tr key={k}><th>{rotulos[k]}</th><td>{String(antes?.[k]??'Não informado')}</td><td>{String(depois?.[k]??'Não informado')}</td></tr>)}</tbody></table></div>;
}

export function VincularRecebimentos({cadastros,atualizar}:{cadastros:TerceiroCadastro[];atualizar:()=>Promise<void>}){
  const [itens,setItens]=useState<EntradaTerceiro[]>([]),[pagina,setPagina]=useState(1),[total,setTotal]=useState(0),[busca,setBusca]=useState(''),[alvo,setAlvo]=useState<EntradaTerceiro|null>(null),[cadastro,setCadastro]=useState(''),[motivo,setMotivo]=useState(''),[erro,setErro]=useState(''),[ocupado,setOcupado]=useState(false);
  const conferir=useOperacaoConferida(),protecao=useAlteracoesNaoSalvas({cadastro,motivo},'Vínculo do recebimento',alvo?.id??null);
  async function carregar(p=1){try{const d=(await api.get<{itens:EntradaTerceiro[];total:number}>('/graos/terceiros/entradas/',{params:{pagina:p,busca,sem_vinculo:true}})).data;setItens(d.itens);setTotal(d.total);setPagina(p);setErro('');}catch{setErro('Não foi possível consultar os recebimentos.');}}
  async function salvar(e:FormEvent){e.preventDefault();if(!alvo||ocupado)return;setOcupado(true);try{const chave=crypto.randomUUID();await conferir(()=>api.post(`/graos/terceiros/entradas/${alvo.id}/vincular/`,{terceiro:Number(cadastro),versao:alvo.versao,motivo},{headers:{'Idempotency-Key':chave}}));setAlvo(null);setCadastro('');setMotivo('');protecao.marcarSalvo({cadastro:'',motivo:''});await carregar();await atualizar();}catch{setErro('Vínculo não concluído. Confira versão, permissões e cadastro.');}finally{setOcupado(false);}}
  return <details onToggle={e=>{if(e.currentTarget.open)void carregar();}}><summary>Vincular recebimentos antigos</summary><p>Confira documento, data e cadastro. Nomes iguais não comprovam identidade. O vínculo preserva pesos, saldos e histórico.</p>{erro&&<p role="alert">{erro}</p>}<label>Buscar recebimentos sem vínculo<input value={busca} onChange={e=>setBusca(e.target.value)}/></label><button type="button" onClick={()=>void carregar()}>Pesquisar recebimentos antigos</button><p>{total} recebimento(s) sem vínculo</p>{itens.map(i=><p key={i.id}>#{i.id} · {i.depositante} · {i.data_entrada} · {i.documento||'Sem documento'} · {i.cultura}/{i.safra} · {formatarNumero(i.peso_liquido_kg)} kg <BotaoAcao acao="editar" type="button" disabled={i.movimentos.some(m=>m.tipo==='entrada'&&m.estornado)} motivoBloqueio="Recebimento estornado: histórico preservado." onClick={async()=>{if(await protecao.confirmarDescarte()){setAlvo(i);setCadastro('');setMotivo('');}}}>Conferir vínculo #{i.id}</BotaoAcao></p>)}<div className="acoes"><button type="button" disabled={pagina===1} onClick={()=>void carregar(pagina-1)}>Página anterior</button><span>Página {pagina}</span><button type="button" disabled={pagina*25>=total} onClick={()=>void carregar(pagina+1)}>Próxima página</button></div>{alvo&&<form className="formulario" onSubmit={salvar}><h4>Vincular recebimento #{alvo.id}</h4><label>Cadastro confirmado<select required value={cadastro} onChange={e=>setCadastro(e.target.value)}><option value="">Selecione</option>{cadastros.filter(t=>t.ativo).map(t=><option key={t.id} value={t.id}>{t.codigo} · {t.nome}</option>)}</select></label><label>Justificativa do vínculo<textarea required maxLength={500} value={motivo} onChange={e=>setMotivo(e.target.value)}/></label><BotaoAcao acao="editar" disabled={ocupado}>Confirmar vínculo manual</BotaoAcao><button type="button" onClick={async()=>{if(await protecao.confirmarDescarte())setAlvo(null);}}>Cancelar vínculo</button></form>}</details>;
}

const operacoes:Record<string,string>={credito_producao:'Entradas de produção',transferencia_terceiro:'Recebido de terceiros (sem produção)',ajuste:'Ajustes',entrega:'Saídas de vendas',reserva:'Reservas',liberacao:'Liberações de reserva',devolucao:'Devoluções',estorno:'Estornos',transferencia_saida:'Transferências de saída',transferencia_entrada:'Transferências recebidas',entrada:'Recebimentos de terceiros',saida:'Retiradas de terceiros',transferencia:'Transferências para CAD/PRO',edicao:'Correções'};
type Conciliacao={operacoes_terceiros:{operacao:string;delta_kg:string}[];operacoes:{operacao:string;delta_kg:string}[];saldo_proprio_kg:string;saldo_terceiros_kg:string;estoque_total_kg:string;diferenca_proprio_kg:string;diferenca_terceiros_kg:string;ultima_contagem:{data_contagem:string;contado_kg:string;saldo_registrado_kg:string;diferenca_kg:string}|null;aviso:string};
export function ConciliacaoEstoque({armazens}:{armazens:ArmazemGraos[]}){
  const [form,setForm]=useState({armazem:'',cultura:'Soja',safra:''}),[dados,setDados]=useState<Conciliacao|null>(null),[erro,setErro]=useState(''),[ocupado,setOcupado]=useState(false);
  async function consultar(e:FormEvent){e.preventDefault();setOcupado(true);setDados(null);try{setDados((await api.get<Conciliacao>('/graos/conciliacao-estoque/',{params:form})).data);setErro('');}catch{setErro('Não foi possível conciliar. Confira filtros e acesso a Produção e saldos.');}finally{setOcupado(false);}}
  return <details><summary>Conciliação de estoque e movimentos</summary><form className="formulario" onSubmit={consultar}><label>Armazém da conciliação<select required value={form.armazem} onChange={e=>setForm({...form,armazem:e.target.value})}><option value="">Selecione</option>{armazens.map(a=><option key={a.id} value={a.id}>{a.nome}</option>)}</select></label><label>Produto da conciliação<select value={form.cultura} onChange={e=>setForm({...form,cultura:e.target.value})}>{['Soja','Milho','Trigo'].map(c=><option key={c}>{c}</option>)}</select></label><label>Safra da conciliação<input required maxLength={20} value={form.safra} onChange={e=>setForm({...form,safra:e.target.value})}/></label><button disabled={ocupado}>Consultar conciliação</button></form>{erro&&<p role="alert">{erro}</p>}{dados&&<><p>Próprio: {formatarNumero(dados.saldo_proprio_kg)} kg · Terceiros: {formatarNumero(dados.saldo_terceiros_kg)} kg · Total físico registrado: {formatarNumero(dados.estoque_total_kg)} kg</p><p>Diferença entre saldo e movimentos: próprio {formatarNumero(dados.diferenca_proprio_kg)} kg · terceiros {formatarNumero(dados.diferenca_terceiros_kg)} kg</p>{dados.operacoes.map(o=><p key={o.operacao}>{operacoes[o.operacao]||o.operacao.split('_').join(' ')}: {formatarNumero(o.delta_kg)} kg</p>)}<h4>Movimentos de terceiros</h4>{dados.operacoes_terceiros.map(o=><p key={o.operacao}>{operacoes[o.operacao]||o.operacao.split('_').join(' ')}: {formatarNumero(o.delta_kg)} kg</p>)}{dados.ultima_contagem?<p>Última contagem ({dados.ultima_contagem.data_contagem}): {formatarNumero(dados.ultima_contagem.contado_kg)} kg · registrado naquela conferência: {formatarNumero(dados.ultima_contagem.saldo_registrado_kg)} kg · diferença física: {formatarNumero(dados.ultima_contagem.diferenca_kg)} kg</p>:<p>Nenhuma contagem física para estes filtros.</p>}<p>{dados.aviso}</p></>}</details>;
}
