import { useEffect, useRef, useState } from "react";
import { api } from "../api/propriedades";
import { BotaoAcao } from "./AcoesContext";
import { ArmazemGraos } from "../api/cargasColhidas";
import { formatarNumero } from "../utils/numeros";
import { formatarData, formatarDataHora } from "../utils/datas";
import { useConfirmacaoCompacta } from "./ConfirmacaoCompacta";
type Contagem={id:number;armazem_nome:string;cultura:string;safra:string;data_contagem:string;contado_kg:string;saldo_registrado_kg:string;saldo_proprio_kg:string;saldo_terceiros_kg:string;diferenca_kg:string;justificativa:string;responsavel:string;registrado_em:string};
export default function ConferenciaEstoque({armazens}:{armazens:ArmazemGraos[]}) {
  const confirmar=useConfirmacaoCompacta();
  const [aberto,setAberto]=useState(false),[registros,setRegistros]=useState<Contagem[]>([]),[erro,setErro]=useState(""),[sucesso,setSucesso]=useState(""),[ocupado,setOcupado]=useState(false);
  const [form,setForm]=useState({armazem:0,cultura:"Soja",safra:"",data_contagem:`${new Date().getFullYear()}-${String(new Date().getMonth()+1).padStart(2,"0")}-${String(new Date().getDate()).padStart(2,"0")}`,contado_kg:"",justificativa:""});
  const [previa,setPrevia]=useState<{saldo_registrado_kg:string;diferenca_kg:string}|null>(null);
  const trava=useRef(false),reenvio=useRef({assinatura:"",chave:""});
  useEffect(()=>{if(!aberto)return;let vigente=true;void api.get<Contagem[]>("/core/conferencia-estoque/").then(r=>{if(vigente)setRegistros(r.data);}).catch(()=>{if(vigente)setErro("Não foi possível consultar as contagens.");});return()=>{vigente=false;};},[aberto]);
  useEffect(()=>{setPrevia(null);if(!aberto||!form.armazem||!form.safra.trim()||!form.contado_kg)return;let vigente=true;void api.get<{saldo_registrado_kg:string;diferenca_kg:string}>("/core/conferencia-estoque/previa/",{params:{armazem:form.armazem,cultura:form.cultura,safra:form.safra,contado_kg:form.contado_kg}}).then(r=>{if(vigente)setPrevia(r.data);}).catch(()=>{if(vigente)setPrevia(null);});return()=>{vigente=false;};},[aberto,form.armazem,form.cultura,form.safra,form.contado_kg]);
  async function salvar(){if(trava.current)return;trava.current=true;setOcupado(true);setErro("");setSucesso("");try{if(!(await confirmar({titulo:"Registrar conferência física",confirmar:"Registrar contagem",mensagem:"O registro compara a contagem com o saldo atual no momento da gravação. A diferença e a justificativa serão preservadas, sem ajuste automático."})))return;const assinatura=JSON.stringify(form);if(reenvio.current.assinatura!==assinatura)reenvio.current={assinatura,chave:crypto.randomUUID()};const {data}=await api.post<Contagem>("/core/conferencia-estoque/",{...form,chave_idempotencia:reenvio.current.chave});setRegistros(itens=>[data,...itens.filter(i=>i.id!==data.id)].slice(0,50));setSucesso(`Contagem #${data.id} registrada. Diferença: ${formatarNumero(data.diferenca_kg)} kg. Saldo preservado.`);}catch(e){const falha=e as {response?:{data?:unknown}};setErro(falha.response?.data?JSON.stringify(falha.response.data):"Não foi possível registrar. Tente novamente com os mesmos dados.");}finally{trava.current=false;setOcupado(false);}}
  return <details className="card" onToggle={e=>setAberto(e.currentTarget.open)}><summary>Conferência física do estoque de grãos</summary><p>Compare o mesmo armazém, produto e safra. O saldo inclui produção própria e terceiros. A referência é o saldo atual na gravação, mesmo para contagem com data anterior.</p>{previa&&<p role="status">Saldo atual: {formatarNumero(previa.saldo_registrado_kg)} kg · diferença (físico − sistema): <strong>{formatarNumero(previa.diferenca_kg)} kg</strong>. O saldo será conferido novamente ao registrar.</p>}<form className="formulario" onSubmit={e=>{e.preventDefault();void salvar();}}><label>Armazém da contagem<select required value={form.armazem||""} onChange={e=>setForm({...form,armazem:Number(e.target.value)})}><option value="">Selecione</option>{armazens.map(a=><option key={a.id} value={a.id}>{a.nome}</option>)}</select></label><label>Produto da contagem<select value={form.cultura} onChange={e=>setForm({...form,cultura:e.target.value})}>{["Soja","Milho","Trigo"].map(v=><option key={v}>{v}</option>)}</select></label><label>Safra da contagem<input required maxLength={20} value={form.safra} onChange={e=>setForm({...form,safra:e.target.value})}/></label><label>Data da contagem<input required type="date" value={form.data_contagem} onChange={e=>setForm({...form,data_contagem:e.target.value})}/></label><label>Contagem física (kg)<input required type="number" min="0" step="0.001" value={form.contado_kg} onChange={e=>setForm({...form,contado_kg:e.target.value})}/></label><label>Justificativa da conferência<textarea required maxLength={2000} value={form.justificativa} onChange={e=>setForm({...form,justificativa:e.target.value})}/></label><BotaoAcao acao="cadastrar" type="submit" disabled={ocupado}>{ocupado?"Registrando…":"Registrar contagem física"}</BotaoAcao></form>{erro&&<p role="alert" className="erro">{erro}</p>}{sucesso&&<p role="status">{sucesso}</p>}<p>Últimas {registros.length} conferências registradas.</p>{registros.map(c=><article key={c.id}><h4>Contagem #{c.id} · {c.armazem_nome} · {c.cultura} / {c.safra}</h4><p>{formatarData(c.data_contagem)} · físico {formatarNumero(c.contado_kg)} kg · sistema {formatarNumero(c.saldo_registrado_kg)} kg · diferença <strong>{formatarNumero(c.diferenca_kg)} kg</strong></p><p>Próprio: {formatarNumero(c.saldo_proprio_kg)} kg · terceiros: {formatarNumero(c.saldo_terceiros_kg)} kg.</p><p>{c.justificativa} · {c.responsavel} · registrado em {formatarDataHora(c.registrado_em)}</p></article>)}</details>;
}
