import { useEffect, useRef, useState } from "react";
import { api } from "../api/propriedades";
import { useAcoes } from "./AcoesContext";
import { obterGeracaoSessao } from "../auth/sessionCoordinator";
import { Modulo } from "../api/usuarios";
export function useRascunhoAutomatico<T extends object>(contexto:Modulo, dados:T, restaurar:(dados:T)=>void) {
 const permitido=useAcoes()("cadastrar");const [salvo,setSalvo]=useState<T|null>(null);const [mensagem,setMensagem]=useState("");const [pronto,setPronto]=useState(false);
 const inicial=useRef(JSON.stringify(dados));const ultimo=useRef(inicial.current);const timer=useRef<number | undefined>(undefined);const fila=useRef(Promise.resolve());const ativo=useRef(true);const geracao=useRef(obterGeracaoSessao());const refRestaurar=useRef(restaurar);refRestaurar.current=restaurar;
 const estadoAtual=useRef({dados,pronto,salvo,permitido});estadoAtual.current={dados,pronto,salvo,permitido};
 const valido=()=>ativo.current&&geracao.current===obterGeracaoSessao();
 useEffect(()=>{ativo.current=true;if(!permitido)return;api.get<{dados:T|null}>(`/core/rascunhos/${contexto}/`).then(({data})=>{if(valido()){setSalvo(data.dados);setPronto(true);}}).catch(()=>{if(valido())setMensagem("Não foi possível carregar o rascunho. O formulário continua disponível.");});return()=>{ativo.current=false;window.clearTimeout(timer.current);const e=estadoAtual.current;const texto=JSON.stringify(e.dados);if(e.permitido&&e.pronto&&!e.salvo&&texto!==ultimo.current&&geracao.current===obterGeracaoSessao()){ultimo.current=texto;fila.current=fila.current.then(async()=>{if(geracao.current===obterGeracaoSessao())try{await api.put(`/core/rascunhos/${contexto}/`,{dados:e.dados});}catch{/* A interface já encerrou; nenhum lançamento é feito. */}});}};},[contexto,permitido]);
 const serializado=JSON.stringify(dados);
 useEffect(()=>{if(!permitido||!pronto||salvo||serializado===ultimo.current)return;window.clearTimeout(timer.current);timer.current=window.setTimeout(()=>{const snapshot=JSON.parse(serializado) as T;ultimo.current=serializado;fila.current=fila.current.then(async()=>{if(geracao.current!==obterGeracaoSessao())return;try{await api.put(`/core/rascunhos/${contexto}/`,{dados:snapshot});if(valido())setMensagem("Rascunho salvo automaticamente na sua conta.");}catch{ultimo.current="";if(valido())setMensagem("Falha ao salvar rascunho; mantenha esta tela aberta.");}});},1000);return()=>window.clearTimeout(timer.current);},[serializado,pronto,salvo,permitido,contexto]);
 function limpar(valorInicial:T){window.clearTimeout(timer.current);ultimo.current=JSON.stringify(valorInicial);setSalvo(null);fila.current=fila.current.then(async()=>{if(geracao.current!==obterGeracaoSessao())return;try{await api.delete(`/core/rascunhos/${contexto}/`);if(valido())setMensagem("");}catch{if(valido())setMensagem("Lançamento registrado, mas o rascunho não pôde ser removido. Descarte-o antes de reutilizar.");}});}
 const aviso=permitido?<aside className="card nao-imprimir" aria-label="Rascunho automático">{salvo?<><p>Há um formulário não concluído salvo na sua conta. Restaurá-lo não registra uma operação.</p><button type="button" onClick={()=>{ultimo.current=JSON.stringify(salvo);refRestaurar.current(salvo);setSalvo(null);setMensagem("Rascunho restaurado. Confira os dados antes de confirmar.");}}>Restaurar rascunho</button><button type="button" className="secundario" onClick={()=>limpar(dados)}>Descartar rascunho</button></>:<small role="status">{mensagem||"O formulário será salvo automaticamente após a edição."}</small>}</aside>:null;
 return {aviso,limpar};
}
