# Generated by Django 5.1.15 on 2026-10-02 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritoFiltro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contexto', models.CharField(max_length=40)),
                ('nome', models.CharField(max_length=80)),
                ('filtros', models.JSONField(default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filtros_favoritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('nome', 'id'),
                'constraints': [models.UniqueConstraint(fields=('usuario', 'contexto', 'nome'), name='core_favorito_usuario_contexto_nome')],
            },
        ),
        migrations.CreateModel(
            name='RegistroAlteracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_nome', models.CharField(max_length=150)),
                ('modulo', models.CharField(max_length=40)),
                ('entidade', models.CharField(max_length=100)),
                ('registro_id', models.CharField(max_length=100)),
                ('acao', models.CharField(max_length=16)),
                ('alteracoes', models.JSONField(default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-criado_em', '-id'),
                'indexes': [models.Index(fields=['modulo', 'entidade', 'registro_id'], name='core_historico_registro')],
            },
        ),
    ]
