# Generated by Django 5.1.15 on 2026-10-03 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_favoritofiltro_configuracao_rascunhoformulario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoLancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidade', models.CharField(max_length=30)),
                ('registro_id', models.CharField(max_length=36)),
                ('nome', models.CharField(max_length=160)),
                ('tipo', models.CharField(max_length=40)),
                ('tamanho', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('conteudo', models.BinaryField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-criado_em', '-id'),
                'indexes': [models.Index(fields=['entidade', 'registro_id'], name='core_anexo_registro')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('excluido_em__isnull', True)), fields=('entidade', 'registro_id', 'sha256'), name='core_anexo_ativo_hash')],
            },
        ),
    ]
