import { FormEvent, useEffect, useRef, useState } from "react";
import { api } from "../../api/propriedades";
import { MODULOS } from "../../api/usuarios";
type Registro = { id: number; usuario_nome: string; modulo: string; entidade: string; registro_id: string; acao: string; criado_em: string; alteracoes: Record<string, {antes: unknown; depois: unknown}> };
type Pagina = { count: number; next: string | null; previous: string | null; results: Registro[] };
const texto = (valor: unknown): string => valor === null || valor === undefined ? "—" : typeof valor === "object" ? JSON.stringify(valor) : String(valor);
export default function HistoricoPage() {
 const [dados, setDados] = useState<Pagina | null>(null); const [filtros, setFiltros] = useState({modulo:"", usuario_nome:"", acao:"", registro_id:""}); const [aplicados, setAplicados] = useState(filtros); const [pagina, setPagina] = useState(1); const [erro, setErro] = useState(""); const [carregando, setCarregando] = useState(false); const consulta = useRef(0);
 async function carregar(numero = 1, params = filtros) { const id = ++consulta.current; setCarregando(true); setErro(""); try { const {data} = await api.get<Pagina>("/core/historico/", {params:{...params, page:numero}}); if (id === consulta.current) {setDados(data); setPagina(numero); setAplicados(params);} } catch { if (id === consulta.current) setErro("Não foi possível consultar o histórico. É necessário acesso de administrador."); } finally {if (id === consulta.current) setCarregando(false);} }
 useEffect(() => {void carregar(); return () => {consulta.current++;};}, []);
 return <section className="card modulo-historico"><h2>Histórico de alterações</h2><p>Registro das alterações realizadas pelo aplicativo a partir desta atualização. Senhas e credenciais não são exibidas.</p><form className="painel-filtros nao-imprimir" onSubmit={(e:FormEvent) => {e.preventDefault(); void carregar();}}><label>Módulo<select value={filtros.modulo} onChange={e => setFiltros({...filtros, modulo:e.target.value})}><option value="">Todos</option>{MODULOS.map(([id,nome]) => <option key={id} value={id}>{nome}</option>)}<option value="usuarios">Usuários</option></select></label><label>Usuário<input value={filtros.usuario_nome} maxLength={150} onChange={e => setFiltros({...filtros, usuario_nome:e.target.value})} /></label><label>Ação<select value={filtros.acao} onChange={e => setFiltros({...filtros, acao:e.target.value})}><option value="">Todas</option><option value="cadastrar">Cadastro</option><option value="editar">Edição</option><option value="excluir">Exclusão</option></select></label><label>Nº do registro<input value={filtros.registro_id} maxLength={100} onChange={e => setFiltros({...filtros, registro_id:e.target.value})} /></label><button disabled={carregando}>{carregando ? "Consultando..." : "Consultar histórico"}</button></form>
 {erro && <p role="alert" className="erro">{erro}</p>}{dados && <><p role="status">{dados.count} alterações encontradas · página {pagina}</p>{!dados.results.length && <p>Nenhuma alteração encontrada.</p>}<div className="historico-lista">{dados.results.map(item => <details key={item.id}><summary><strong>{item.usuario_nome}</strong><span>{MODULOS.find(([id]) => id === item.modulo)?.[1] || item.modulo} · {item.entidade} #{item.registro_id}</span><span>{item.acao} · {new Date(item.criado_em).toLocaleString("pt-BR")}</span></summary><div className="tabela-responsiva"><table><thead><tr><th>Campo</th><th>Antes</th><th>Depois</th></tr></thead><tbody>{Object.entries(item.alteracoes).map(([campo, valores]) => <tr key={campo}><th>{campo}</th><td>{texto(valores.antes)}</td><td>{texto(valores.depois)}</td></tr>)}</tbody></table></div></details>)}</div><div className="acoes"><button className="secundario" disabled={carregando || !dados.previous} onClick={() => void carregar(pagina-1,aplicados)}>Anterior</button><button className="secundario" disabled={carregando || !dados.next} onClick={() => void carregar(pagina+1,aplicados)}>Próxima</button></div></>}
 </section>;
}
