# Generated by Django 5.1.15 on 2026-07-26 02:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propriedades', '0003_propriedade_area_calculada_hectares_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.CharField(blank=True, max_length=240)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('propriedade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locais_estoque', to='propriedades.propriedade')),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='LoteEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('observacoes', models.CharField(blank=True, max_length=240)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='estoque.localestoque')),
            ],
            options={
                'ordering': ('data_validade', 'codigo'),
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=8)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('custo_unitario', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('data_movimento', models.DateField(default=django.utils.timezone.localdate)),
                ('documento_fiscal', models.CharField(blank=True, max_length=80)),
                ('safra', models.CharField(blank=True, max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_estoque', to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='estoque.loteestoque')),
                ('propriedade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_estoque', to='propriedades.propriedade')),
            ],
            options={
                'ordering': ('-data_movimento', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ProdutoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160)),
                ('categoria', models.CharField(choices=[('insumo', 'Insumo'), ('herbicida', 'Herbicida'), ('fungicida', 'Fungicida'), ('fertilizante', 'Fertilizante'), ('semente', 'Semente'), ('outro', 'Outro')], max_length=20)),
                ('unidade', models.CharField(choices=[('kg', 'Quilograma'), ('l', 'Litro'), ('un', 'Unidade'), ('sc', 'Saca'), ('t', 'Tonelada')], max_length=5)),
                ('fabricante', models.CharField(blank=True, max_length=120)),
                ('estoque_minimo', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('nome',),
                'constraints': [models.UniqueConstraint(fields=('nome', 'fabricante'), name='estoque_produto_nome_fabricante_unico')],
            },
        ),
        migrations.AddField(
            model_name='loteestoque',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='estoque.produtoestoque'),
        ),
        migrations.AddConstraint(
            model_name='localestoque',
            constraint=models.UniqueConstraint(fields=('nome', 'propriedade'), name='estoque_local_nome_propriedade_unico'),
        ),
        migrations.AddIndex(
            model_name='movimentacaoestoque',
            index=models.Index(fields=['lote', 'data_movimento'], name='estoque_lote_data_idx'),
        ),
        migrations.AddConstraint(
            model_name='movimentacaoestoque',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gt', 0)), name='estoque_movimento_quantidade_positiva'),
        ),
        migrations.AddConstraint(
            model_name='movimentacaoestoque',
            constraint=models.CheckConstraint(condition=models.Q(('custo_unitario__isnull', True), ('custo_unitario__gte', 0), _connector='OR'), name='estoque_movimento_custo_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='loteestoque',
            constraint=models.UniqueConstraint(fields=('produto', 'local', 'codigo'), name='estoque_lote_produto_local_codigo_unico'),
        ),
    ]
