# Generated by Django 5.1.15 on 2026-09-11 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
        ('financeiro', '0002_codigo_barras'),
    ]

    operations = [
        migrations.AddField(
            model_name='loteestoque',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes_estoque', to='financeiro.parceirofinanceiro'),
        ),
        migrations.AlterField(
            model_name='loteestoque',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='estoque.localestoque'),
        ),
        migrations.AddConstraint(
            model_name='loteestoque',
            constraint=models.UniqueConstraint(condition=models.Q(('local__isnull', True)), fields=('produto', 'fornecedor', 'codigo'), name='estoque_lote_prod_forn_codigo_unico'),
        ),
    ]
