# Generated by Django 5.1.15 on 2026-09-14 10:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_loteestoque_fornecedor_alter_loteestoque_local_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraEstoque',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('assinatura', models.CharField(editable=False, max_length=64)),
                ('cultura', models.CharField(blank=True, max_length=100)),
                ('quantidade_embalagens', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('embalagem', models.CharField(max_length=20)),
                ('conteudo_embalagem', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('custo_embalagem', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=24)),
                ('movimento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='compra', to='estoque.movimentacaoestoque')),
            ],
            options={
                'ordering': ('-movimento__data_movimento', '-movimento_id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('conteudo_embalagem__gt', 0), ('custo_embalagem__gte', 0), ('quantidade_embalagens__gt', 0), ('valor_total__gte', 0)), name='estoque_compra_valores_validos')],
            },
        ),
    ]
