# Generated by Django 5.1.15 on 2026-09-22 15:41

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_compraestoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='compraestoque',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compraestoque',
            name='valor_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddConstraint(
            model_name='compraestoque',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('data_pagamento__isnull', True), ('valor_pago__isnull', True)), models.Q(('data_pagamento__isnull', False), ('valor_pago__gte', 0), ('valor_pago__isnull', False)), _connector='OR'), name='estoque_compra_pagamento_valido'),
        ),
    ]
