# Generated by Django 5.1.15 on 2026-09-28 16:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_compraestoque_data_pagamento_and_more'),
        ('financeiro', '0004_lancamentofinanceiro_total_boletos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaturamentoInsumo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assinatura', models.CharField(max_length=64)),
                ('data_envio', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('resumo', models.JSONField()),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.parceirofinanceiro')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.produtoestoque')),
            ],
            options={
                'ordering': ('-criado_em',),
            },
        ),
        migrations.CreateModel(
            name='BaixaFaturamentoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movimento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='baixa_faturamento', to='estoque.movimentacaoestoque')),
                ('faturamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baixas', to='estoque.faturamentoinsumo')),
            ],
        ),
    ]
