# Generated by Django 5.1.15 on 2026-09-29 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_faturamento_insumos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='faturamentoinsumo',
            name='excluido_em',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='faturamentoinsumo',
            name='excluido_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faturamentos_insumos_excluidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
