import { useEffect, useState } from "react";
import { api } from "../../api/propriedades";
import { EntradaTerceiro, opcoesTerceiros, filtroTerceiro } from "../../api/terceiros";
import { formatarNumero } from "../../utils/numeros";
import { formatarData } from "../../utils/datas";
type Extrato={pagina:number;total:number;itens:{id:number;entrada:number;data:string;tipo:string;cultura:string;safra:string;armazem:string;delta_kg:string;saldo_acumulado_kg:string;documento:string;motivo:string;responsavel:string;estorno_de:number|null;estornado:boolean}[]};
export default function ExtratoTerceiro({entradas,ativo}:{entradas:EntradaTerceiro[];ativo:boolean}) {
  const [aberto,setAberto]=useState(false),[depositante,setDepositante]=useState(""),[cultura,setCultura]=useState(""),[safra,setSafra]=useState(""),[pagina,setPagina]=useState(1),[dados,setDados]=useState<Extrato|null>(null),[erro,setErro]=useState(""),[ocupado,setOcupado]=useState(false);
  useEffect(()=>{if(!ativo||!aberto||!depositante)return;let vigente=true;setOcupado(true);setDados(null);setErro("");void api.get<Extrato>("/graos/terceiros/extrato/",{params:{...filtroTerceiro(depositante),cultura,safra,pagina}}).then(r=>{if(vigente)setDados(r.data);}).catch(()=>{if(vigente)setErro("Não foi possível carregar o extrato.");}).finally(()=>{if(vigente)setOcupado(false);});return()=>{vigente=false;};},[ativo,aberto,depositante,cultura,safra,pagina,entradas]);
  const opcoes=(campo:"depositante"|"cultura"|"safra")=>[...new Map(entradas.map(i=>[i[campo].trim().toLocaleLowerCase("pt-BR"),i[campo].trim()])).values()].sort();
  return <details onToggle={e=>setAberto(e.currentTarget.open)}><summary>Extrato por terceiro</summary><p>Movimentos por data, incluindo correções e estornos. O saldo acumulado é separado por produto e safra e inclui todos os armazéns. O cadastro identifica o terceiro. Recebimentos sem vínculo são consultados separadamente; produto e safra exibem a classificação atual do recebimento.</p><div className="painel-filtros"><label>Terceiro do extrato<select value={depositante} onChange={e=>{setDepositante(e.target.value);setDados(null);setPagina(1);}}><option value="">Selecione</option>{opcoesTerceiros(entradas).map(v=><option key={v.chave} value={v.chave}>{v.nome}</option>)}</select></label><label>Produto do extrato<select value={cultura} onChange={e=>{setCultura(e.target.value);setPagina(1);}}><option value="">Todos</option>{opcoes("cultura").map(v=><option key={v}>{v}</option>)}</select></label><label>Safra do extrato<select value={safra} onChange={e=>{setSafra(e.target.value);setPagina(1);}}><option value="">Todas</option>{opcoes("safra").map(v=><option key={v}>{v}</option>)}</select></label></div>{erro&&<p className="erro" role="alert">{erro}</p>}{ocupado&&<p role="status">Carregando extrato…</p>}{dados&&<><div className="tabela-scroll"><table><thead><tr><th>Data / movimento</th><th>Produto / safra / armazém</th><th>Variação (kg)</th><th>Saldo acumulado (kg)</th><th>Referência / responsável</th></tr></thead><tbody>{dados.itens.map(m=><tr key={m.id}><td>{formatarData(m.data)} · {m.tipo} #{m.id}{m.estorno_de&&<small>Estorno de #{m.estorno_de}</small>}{m.estornado&&<small>Estornado, com efeito compensado no extrato</small>}</td><td>{m.cultura} · {m.safra}<small>{m.armazem}</small></td><td>{formatarNumero(m.delta_kg)}</td><td>{formatarNumero(m.saldo_acumulado_kg)}</td><td>Romaneio #{m.entrada} · {m.documento}<small>{m.responsavel} · {m.motivo}</small></td></tr>)}</tbody></table></div><p role="status">{dados.total} movimentos · página {dados.pagina}</p><div className="acoes"><button type="button" className="secundario" disabled={ocupado||pagina===1} onClick={()=>setPagina(p=>p-1)}>Anterior do extrato</button><button type="button" className="secundario" disabled={ocupado||pagina*25>=dados.total} onClick={()=>setPagina(p=>p+1)}>Próxima do extrato</button></div></>}</details>;
}
