import { dadosRomaneioTerceiro } from "./romaneioTerceiro";
import { FormEvent, useEffect, useRef, useState } from "react";
import axios from "axios";
import { ArmazemGraos } from "../../api/cargasColhidas";
import { EntradaTerceiro, NovaEntradaTerceiro, SaidaTerceiro, listarTerceiros, registrarEntradaTerceiro, registrarSaidaTerceiro, estornarTerceiro, previaTerceiro, editarEntradaTerceiro, excluirEntradaTerceiro } from "../../api/terceiros";
import FormularioValidado from "../../components/FormularioValidado";
import ComprovanteLancamento from "../../components/ComprovanteLancamento";
import { BotaoAcao } from "../../components/AcoesContext";
import { formatarNumero } from "../../utils/numeros";
import { useAlteracoesNaoSalvas } from "../../components/AlteracoesNaoSalvas";
import { quantidadeContrato } from "../CadastrosAgricolas/ContratosComerciais";
const converterDecimalDigitado=(valor:string)=>{try{return quantidadeContrato(valor);}catch{return null;}};

const hoje=()=>{const data=new Date();return `${data.getFullYear()}-${String(data.getMonth()+1).padStart(2,"0")}-${String(data.getDate()).padStart(2,"0")}`;};
const novaEntrada=():NovaEntradaTerceiro=>({depositante:"",cultura:"Soja",safra:"",armazem:0,peso_bruto_kg:"",umidade_percentual:"",impureza_percentual:"0",defeitos_percentual:"0",ph:null,ph_minimo:"0",desconto_ph_por_ponto:"0",data_entrada:hoje(),placa:"",motorista:"",documento:"",observacoes:""});
const novaSaida=():SaidaTerceiro=>({quantidade_kg:"",data_movimento:hoje(),destino:"",placa:"",motorista:"",documento:"",observacoes:""});
const dataBR=(data:string)=>data.split("-").reverse().join("/");
function erroTexto(falha:unknown){const dados=axios.isAxiosError(falha)?falha.response?.data:null;return dados?JSON.stringify(dados):"Não foi possível concluir. Confira a conexão e tente novamente.";}

export default function ProducaoTerceiros({armazens,atualizarArmazens,inicialmenteAberto=false,ativo=true}:{armazens:ArmazemGraos[];atualizarArmazens:()=>Promise<void>;inicialmenteAberto?:boolean;ativo?:boolean}){
  const [aberto,setAberto]=useState(inicialmenteAberto),[itens,setItens]=useState<EntradaTerceiro[]>([]),[form,setForm]=useState(novaEntrada),[saida,setSaida]=useState(novaSaida),[alvo,setAlvo]=useState<number|null>(null),[estorno,setEstorno]=useState<number|null>(null),[motivo,setMotivo]=useState(""),[busca,setBusca]=useState(""),[ocupado,setOcupado]=useState(false),[erro,setErro]=useState(""),[sucesso,setSucesso]=useState("");
  const [editando,setEditando]=useState<EntradaTerceiro|null>(null),[excluindo,setExcluindo]=useState<EntradaTerceiro|null>(null);
  const formularioEntrada=useRef<HTMLDetailsElement>(null);
  const confirmacao=useRef<HTMLDivElement>(null);
  useEffect(()=>{if(excluindo)confirmacao.current?.scrollIntoView({block:"center",behavior:"smooth"});},[excluindo]);
  const [previa,setPrevia]=useState<{peso_liquido_kg:string;desconto_total_percentual:string;desconto_total_kg:string}|null>(null),[erroPrevia,setErroPrevia]=useState("");
  useEffect(()=>{let ativa=true;setPrevia(null);setErroPrevia("");const bruto=converterDecimalDigitado(form.peso_bruto_kg);if(!bruto||!form.umidade_percentual)return;
    const timer=setTimeout(()=>{void previaTerceiro({cultura:form.cultura,peso_bruto_kg:bruto,umidade_percentual:form.umidade_percentual,impureza_percentual:form.impureza_percentual,defeitos_percentual:form.defeitos_percentual,ph:form.cultura==="Trigo"?form.ph||null:null,ph_minimo:form.ph_minimo,desconto_ph_por_ponto:form.desconto_ph_por_ponto}).then(d=>{if(ativa)setPrevia(d);}).catch(f=>{if(ativa)setErroPrevia(erroTexto(f));});},250);
    return()=>{ativa=false;clearTimeout(timer);};
  },[form.cultura,form.peso_bruto_kg,form.umidade_percentual,form.impureza_percentual,form.defeitos_percentual,form.ph,form.ph_minimo,form.desconto_ph_por_ponto]);
  const trava=useRef(false),reenvio=useRef<{assinatura:string;chave:string}|null>(null);
  const protecao=useAlteracoesNaoSalvas({form,saida,motivo},"Produção de terceiros");
  async function carregar(){try{setItens(await listarTerceiros());setErro("");}catch(falha){setErro(erroTexto(falha));}}
  useEffect(()=>{if(inicialmenteAberto && ativo)void carregar();},[inicialmenteAberto,ativo,armazens]);
  async function operar(assinatura:string,acao:(chave:string)=>Promise<EntradaTerceiro>){if(trava.current)return;trava.current=true;setOcupado(true);setErro("");setSucesso("");
    if(reenvio.current?.assinatura!==assinatura)reenvio.current={assinatura,chave:crypto.randomUUID()};
    try{const salvo=await acao(reenvio.current.chave);setItens(atual=>[salvo,...atual.filter(i=>i.id!==salvo.id)]);setForm(novaEntrada());setEditando(null);setExcluindo(null);setSaida(novaSaida());setAlvo(null);setEstorno(null);setMotivo("");reenvio.current=null;protecao.marcarSalvo();setSucesso("Movimentação de terceiros registrada. Produção própria preservada.");void atualizarArmazens().catch(()=>setErro("Registro salvo; atualize para conferir a ocupação do armazém."));}catch(falha){setErro(erroTexto(falha));}finally{trava.current=false;setOcupado(false);}}
  function enviarEntrada(e:FormEvent){e.preventDefault();const peso=converterDecimalDigitado(form.peso_bruto_kg);if(!peso||Number(peso)<=0){setErro("Informe um peso bruto válido maior que zero.");return;}const dados={...form,peso_bruto_kg:peso,ph:form.cultura==="Trigo"?form.ph||null:null};void operar(JSON.stringify([editando?.id,editando?.versao,motivo,dados]),chave=>editando?editarEntradaTerceiro(editando.id,dados,editando.versao,motivo,chave):registrarEntradaTerceiro(dados,chave));}
  async function abrirEdicao(item:EntradaTerceiro){
    if(!(await protecao.confirmarDescarte()))return;
    const bruto=item.peso_bruto_kg===null?"":Number(item.peso_bruto_kg).toLocaleString("pt-BR",{maximumFractionDigits:3});
    setForm({...novaEntrada(),depositante:item.depositante,cultura:item.cultura,safra:item.safra,armazem:item.armazem,peso_bruto_kg:bruto,umidade_percentual:item.umidade_percentual??"",impureza_percentual:item.impureza_percentual??"0",defeitos_percentual:item.defeitos_percentual??"0",ph:item.ph,ph_minimo:item.regra_desconto_aplicada.parcelas?.ph?.minimo??"0",desconto_ph_por_ponto:item.regra_desconto_aplicada.parcelas?.ph?.desconto_por_ponto??"0",data_entrada:item.data_entrada,placa:item.placa,motorista:item.motorista,documento:item.documento,observacoes:item.observacoes});
    setEditando(item);setExcluindo(null);setMotivo("");setAlvo(null);setEstorno(null);if(formularioEntrada.current){formularioEntrada.current.open=true;formularioEntrada.current.scrollIntoView({block:"start",behavior:"smooth"});}protecao.marcarSalvo();
  }
  function enviarSaida(e:FormEvent){e.preventDefault();const peso=converterDecimalDigitado(saida.quantidade_kg);if(!peso||Number(peso)<=0||!alvo){setErro("Informe a quantidade da saída maior que zero.");return;}const dados={...saida,quantidade_kg:peso};void operar(JSON.stringify(["saida",alvo,dados]),chave=>registrarSaidaTerceiro(alvo,dados,chave));}
  const visiveis=itens.filter(i=>`${i.depositante} ${i.propriedade_origem} ${i.cad_pro} ${i.cultura} ${i.safra} ${i.armazem_nome}`.toLocaleLowerCase("pt-BR").includes(busca.toLocaleLowerCase("pt-BR")));
  return <section className="card nao-imprimir"><button className="secundario" type="button" aria-expanded={aberto} onClick={()=>{setAberto(!aberto);if(!aberto)void carregar();}}>Produção de terceiros · entradas e saldo separado</button>
    {aberto&&<><h3>Produção de terceiros</h3><p>O saldo ocupa o armazém e integra o estoque físico. Não entra na produção, área ou média das propriedades cadastradas. Os descontos seguem as mesmas regras das cargas próprias; o estoque recebe o peso líquido calculado.</p>
      {erro&&<p role="alert" className="erro">{erro}</p>}{sucesso&&<p role="status" className="sucesso">{sucesso}</p>}
      <details ref={formularioEntrada}><summary>{editando?`Editar entrada de terceiros #${editando.id}`:"Registrar entrada de terceiros"}</summary><FormularioValidado className="formulario terceiros-formulario" onSubmit={enviarEntrada}>
        <label>Nome do terceiro<input required maxLength={160} value={form.depositante} onChange={e=>setForm({...form,depositante:e.target.value})}/></label>
        <label>Cultura<select value={form.cultura} onChange={e=>setForm({...form,cultura:e.target.value})}>{["Soja","Milho","Trigo"].map(c=><option key={c}>{c}</option>)}</select></label>
        <label>Safra do terceiro<input required maxLength={20} value={form.safra} onChange={e=>setForm({...form,safra:e.target.value})}/></label>
        <label>Armazém de terceiros<select required disabled={!!editando} value={form.armazem||""} onChange={e=>setForm({...form,armazem:Number(e.target.value)})}><option value="">Selecione</option>{armazens.filter(a=>a.ativo).map(a=><option key={a.id} value={a.id}>{a.nome}</option>)}</select></label>
        <label>Data de entrada de terceiros<input required type="date" value={form.data_entrada} onChange={e=>setForm({...form,data_entrada:e.target.value})}/></label>
        <label>Peso bruto (kg)<input required inputMode="decimal" value={form.peso_bruto_kg} onChange={e=>setForm({...form,peso_bruto_kg:e.target.value})}/></label>
        {([ ["umidade_percentual","Umidade (%)"], ["impureza_percentual","Impureza (%)"], ["defeitos_percentual","Avariados (%)"], ["ph","PH"] ] as const).filter(([campo])=>campo!=="ph"||form.cultura==="Trigo").map(([campo,rotulo])=><label key={campo}>{rotulo}<input required={campo!=="ph"} type="number" min="0" max="100" step="0.001" value={form[campo]??""} onChange={e=>setForm({...form,[campo]:e.target.value})}/></label>)}
        <div className="terceiros-resumo" role="status">{previa?<><span>Desconto <strong>{formatarNumero(previa.desconto_total_percentual)}% · {formatarNumero(previa.desconto_total_kg)} kg</strong></span><span>Peso líquido <strong>{formatarNumero(previa.peso_liquido_kg)} kg</strong></span></>:<span>{erroPrevia||"Preencha peso e classificação para conferir o líquido antes de registrar."}</span>}</div>
        <label>Placa da entrada<input maxLength={7} value={form.placa} onChange={e=>setForm({...form,placa:e.target.value})}/></label>
        <label>Motorista da entrada<input maxLength={120} value={form.motorista} onChange={e=>setForm({...form,motorista:e.target.value})}/></label>
        <label>Documento da entrada<input maxLength={120} value={form.documento} onChange={e=>setForm({...form,documento:e.target.value})}/></label>
        <label>Observações da entrada<textarea maxLength={4000} value={form.observacoes} onChange={e=>setForm({...form,observacoes:e.target.value})}/></label>
        {editando&&<label className="terceiros-linha-inteira">Motivo da edição<textarea required maxLength={500} value={motivo} onChange={e=>setMotivo(e.target.value)}/></label>}
        <div className="acoes terceiros-linha-inteira"><BotaoAcao acao={editando?"editar":"cadastrar"} disabled={ocupado} type="submit">{editando?"Salvar edição":"Registrar entrada de terceiros"}</BotaoAcao>{editando&&<button type="button" className="secundario" disabled={ocupado} onClick={async()=>{if(await protecao.confirmarDescarte()){setEditando(null);setForm(novaEntrada());setMotivo("");protecao.marcarSalvo();}}}>Cancelar edição</button>}</div>
      </FormularioValidado></details>
      <div className="painel-filtros"><label>Buscar produção de terceiros<input value={busca} onChange={e=>setBusca(e.target.value)}/></label><button type="button" disabled={ocupado} onClick={()=>void carregar()}>Atualizar terceiros</button></div>
      <p role="status">{visiveis.length} recebimento(s) · Saldo de terceiros nesta consulta: <strong>{formatarNumero(visiveis.reduce((s,i)=>s+Number(i.saldo_kg),0))} kg</strong></p>
      {visiveis.map(i=><article className="item terceiro-recebimento" key={i.id}><div><h4>{i.depositante} · recebimento #{i.id}</h4><p>{i.cultura} · {i.safra} · {i.armazem_nome} · {dataBR(i.data_entrada)}</p><p>{i.peso_bruto_kg!==null&&<>Bruto {formatarNumero(i.peso_bruto_kg)} kg · Desconto {formatarNumero(i.desconto_total_percentual||"0")}% · </>}Líquido {formatarNumero(i.peso_liquido_kg)} kg · Saldo <strong>{formatarNumero(i.saldo_kg)} kg</strong></p>
        <div className="acoes"><ComprovanteLancamento duasVias rotulo="Imprimir" dados={dadosRomaneioTerceiro(i)}/>
        {!i.movimentos.some(m=>m.tipo==="entrada"&&m.estornado)&&<><BotaoAcao acao="editar" disabled={ocupado} type="button" onClick={()=>void abrirEdicao(i)}>Editar entrada</BotaoAcao><BotaoAcao acao="excluir" className="perigo" disabled={ocupado} type="button" onClick={async()=>{if(await protecao.confirmarDescarte()){setExcluindo(i);setEditando(null);setForm(novaEntrada());setMotivo("");setAlvo(null);setEstorno(null);protecao.marcarSalvo();}}}>Excluir entrada</BotaoAcao></>}
        {Number(i.saldo_kg)>0&&<BotaoAcao acao="cadastrar" disabled={ocupado} type="button" onClick={async()=>{if(await protecao.confirmarDescarte()){setAlvo(i.id);setSaida(novaSaida());setEstorno(null);setEditando(null);setExcluindo(null);setForm(novaEntrada());setMotivo("");protecao.marcarSalvo();}}}>Registrar saída de terceiros</BotaoAcao>}</div>
        <details><summary aria-label="Histórico de terceiros">Histórico</summary>{i.movimentos.map(m=><div key={m.id}><p>#{m.id} · {m.tipo} · {dataBR(m.data_movimento)} · {formatarNumero(m.quantidade_kg)} kg · Saldo {formatarNumero(m.saldo_anterior_kg)} → {formatarNumero(m.saldo_posterior_kg)} kg · {m.criado_por_nome}{m.estornado?" · Estornado":""} · {m.destino} · {m.observacoes}</p>{m.tipo!=="estorno"&&m.tipo!=="edicao"&&!m.estornado&&<BotaoAcao acao="excluir" disabled={ocupado} type="button" className="secundario" onClick={async()=>{if(await protecao.confirmarDescarte()){setEstorno(m.id);setMotivo("");setAlvo(null);setEditando(null);setExcluindo(null);setForm(novaEntrada());protecao.marcarSalvo();}}}>Estornar movimento #{m.id}</BotaoAcao>}</div>)}</details>
      </div></article>)}{!visiveis.length&&<p>Nenhuma entrada de terceiros encontrada.</p>}
      {alvo&&<FormularioValidado className="formulario" onSubmit={enviarSaida}><h4>Saída do recebimento #{alvo}</h4><label>Quantidade de terceiros a retirar (kg)<input required inputMode="decimal" value={saida.quantidade_kg} onChange={e=>setSaida({...saida,quantidade_kg:e.target.value})}/></label><label>Data de saída de terceiros<input required type="date" value={saida.data_movimento} onChange={e=>setSaida({...saida,data_movimento:e.target.value})}/></label><label>Destino da saída de terceiros<input required maxLength={160} value={saida.destino} onChange={e=>setSaida({...saida,destino:e.target.value})}/></label><label>Placa da saída<input maxLength={7} value={saida.placa} onChange={e=>setSaida({...saida,placa:e.target.value})}/></label><label>Motorista da saída<input maxLength={120} value={saida.motorista} onChange={e=>setSaida({...saida,motorista:e.target.value})}/></label><label>Documento da saída<input maxLength={120} value={saida.documento} onChange={e=>setSaida({...saida,documento:e.target.value})}/></label><label>Observações da saída<textarea maxLength={4000} value={saida.observacoes} onChange={e=>setSaida({...saida,observacoes:e.target.value})}/></label><div className="acoes"><BotaoAcao acao="cadastrar" type="submit" disabled={ocupado}>Confirmar saída de terceiros</BotaoAcao><button type="button" className="secundario" disabled={ocupado} onClick={async()=>{if(await protecao.confirmarDescarte()){setAlvo(null);setSaida(novaSaida());protecao.marcarSalvo();}}}>Cancelar saída</button></div></FormularioValidado>}
      {excluindo&&<div ref={confirmacao}><FormularioValidado className="formulario confirmacao-exclusao-carga" onSubmit={e=>{e.preventDefault();void operar(JSON.stringify(["excluir",excluindo.id,excluindo.versao,motivo]),chave=>excluirEntradaTerceiro(excluindo.id,excluindo.versao,motivo,hoje(),chave));}}><h4>Excluir entrada de {excluindo.depositante}</h4><p>A exclusão estorna {formatarNumero(excluindo.peso_liquido_kg)} kg e preserva o histórico. Retiradas ativas devem ser estornadas antes.</p><label>Motivo da exclusão<textarea required maxLength={500} value={motivo} onChange={e=>setMotivo(e.target.value)}/></label><div className="acoes"><BotaoAcao acao="excluir" className="perigo" type="submit" disabled={ocupado||!motivo.trim()}>Confirmar exclusão</BotaoAcao><button type="button" className="secundario" disabled={ocupado} onClick={()=>{setExcluindo(null);setMotivo("");}}>Cancelar exclusão</button></div></FormularioValidado></div>}
      {estorno&&<FormularioValidado className="formulario confirmacao-exclusao-carga" onSubmit={e=>{e.preventDefault();void operar(JSON.stringify(["estorno",estorno,motivo]),chave=>estornarTerceiro(estorno,motivo,hoje(),chave));}}><h4>Estornar movimento de terceiros #{estorno}</h4><p>O servidor confere o saldo. O registro original permanece no histórico.</p><label>Motivo do estorno<textarea required maxLength={500} value={motivo} onChange={e=>setMotivo(e.target.value)}/></label><div className="acoes"><BotaoAcao acao="excluir" className="perigo" type="submit" disabled={ocupado||!motivo.trim()}>Confirmar estorno</BotaoAcao><button type="button" className="secundario" disabled={ocupado} onClick={()=>{setEstorno(null);setMotivo("");}}>Cancelar estorno</button></div></FormularioValidado>}
    </>}
  </section>;
}
