import { FormEvent, useRef, useState } from "react";
import axios from "axios";
import { ArmazemGraos } from "../../api/cargasColhidas";
import { EntradaTerceiro, NovaEntradaTerceiro, SaidaTerceiro, listarTerceiros, registrarEntradaTerceiro, registrarSaidaTerceiro, estornarTerceiro } from "../../api/terceiros";
import FormularioValidado from "../../components/FormularioValidado";
import ComprovanteLancamento from "../../components/ComprovanteLancamento";
import { BotaoAcao } from "../../components/AcoesContext";
import { formatarNumero } from "../../utils/numeros";
import { useAlteracoesNaoSalvas } from "../../components/AlteracoesNaoSalvas";
import { quantidadeContrato } from "../CadastrosAgricolas/ContratosComerciais";
const converterDecimalDigitado=(valor:string)=>{try{return quantidadeContrato(valor);}catch{return null;}};

const hoje=()=>{const data=new Date();return `${data.getFullYear()}-${String(data.getMonth()+1).padStart(2,"0")}-${String(data.getDate()).padStart(2,"0")}`;};
const novaEntrada=():NovaEntradaTerceiro=>({depositante:"",propriedade_origem:"",cad_pro:"",cultura:"Soja",safra:"",armazem:0,peso_liquido_kg:"",data_entrada:hoje(),placa:"",motorista:"",documento:"",observacoes:""});
const novaSaida=():SaidaTerceiro=>({quantidade_kg:"",data_movimento:hoje(),destino:"",placa:"",motorista:"",documento:"",observacoes:""});
const dataBR=(data:string)=>data.split("-").reverse().join("/");
function erroTexto(falha:unknown){const dados=axios.isAxiosError(falha)?falha.response?.data:null;return dados?JSON.stringify(dados):"Não foi possível concluir. Confira a conexão e tente novamente.";}

export default function ProducaoTerceiros({armazens,atualizarArmazens}:{armazens:ArmazemGraos[];atualizarArmazens:()=>Promise<void>}){
  const [aberto,setAberto]=useState(false),[itens,setItens]=useState<EntradaTerceiro[]>([]),[form,setForm]=useState(novaEntrada),[saida,setSaida]=useState(novaSaida),[alvo,setAlvo]=useState<number|null>(null),[estorno,setEstorno]=useState<number|null>(null),[motivo,setMotivo]=useState(""),[busca,setBusca]=useState(""),[ocupado,setOcupado]=useState(false),[erro,setErro]=useState(""),[sucesso,setSucesso]=useState("");
  const trava=useRef(false),reenvio=useRef<{assinatura:string;chave:string}|null>(null);
  const protecao=useAlteracoesNaoSalvas({form,saida,motivo},"Produção de terceiros");
  async function carregar(){try{setItens(await listarTerceiros());setErro("");}catch(falha){setErro(erroTexto(falha));}}
  async function operar(assinatura:string,acao:(chave:string)=>Promise<EntradaTerceiro>){if(trava.current)return;trava.current=true;setOcupado(true);setErro("");setSucesso("");
    if(reenvio.current?.assinatura!==assinatura)reenvio.current={assinatura,chave:crypto.randomUUID()};
    try{const salvo=await acao(reenvio.current.chave);setItens(atual=>[salvo,...atual.filter(i=>i.id!==salvo.id)]);setForm(novaEntrada());setSaida(novaSaida());setAlvo(null);setEstorno(null);setMotivo("");reenvio.current=null;protecao.marcarSalvo();setSucesso("Movimentação de terceiros registrada. Produção própria preservada.");void atualizarArmazens().catch(()=>setErro("Registro salvo; atualize para conferir a ocupação do armazém."));}catch(falha){setErro(erroTexto(falha));}finally{trava.current=false;setOcupado(false);}}
  function enviarEntrada(e:FormEvent){e.preventDefault();const peso=converterDecimalDigitado(form.peso_liquido_kg);if(!peso||Number(peso)<=0){setErro("Informe um peso líquido válido maior que zero.");return;}const dados={...form,peso_liquido_kg:peso};void operar(JSON.stringify(["entrada",dados]),chave=>registrarEntradaTerceiro(dados,chave));}
  function enviarSaida(e:FormEvent){e.preventDefault();const peso=converterDecimalDigitado(saida.quantidade_kg);if(!peso||Number(peso)<=0||!alvo){setErro("Informe a quantidade da saída maior que zero.");return;}const dados={...saida,quantidade_kg:peso};void operar(JSON.stringify(["saida",alvo,dados]),chave=>registrarSaidaTerceiro(alvo,dados,chave));}
  const visiveis=itens.filter(i=>`${i.depositante} ${i.propriedade_origem} ${i.cad_pro} ${i.cultura} ${i.safra} ${i.armazem_nome}`.toLocaleLowerCase("pt-BR").includes(busca.toLocaleLowerCase("pt-BR")));
  return <section className="card nao-imprimir"><button className="secundario" type="button" aria-expanded={aberto} onClick={()=>{setAberto(!aberto);if(!aberto)void carregar();}}>Produção de terceiros · entradas e saldo separado</button>
    {aberto&&<><h3>Produção de terceiros</h3><p>O saldo ocupa o armazém e integra o estoque físico. Não entra na produção, área ou média das propriedades cadastradas. Informe o peso líquido já apurado no recebimento.</p>
      {erro&&<p role="alert" className="erro">{erro}</p>}{sucesso&&<p role="status" className="sucesso">{sucesso}</p>}
      <details><summary>Registrar entrada de terceiros</summary><FormularioValidado className="formulario" onSubmit={enviarEntrada}>
        <label>Depositante / produtor terceiro<input required maxLength={160} value={form.depositante} onChange={e=>setForm({...form,depositante:e.target.value})}/></label>
        <label>Propriedade de origem (terceiro)<input maxLength={160} value={form.propriedade_origem} onChange={e=>setForm({...form,propriedade_origem:e.target.value})}/></label>
        <label>CAD/PRO do terceiro<input maxLength={80} value={form.cad_pro} onChange={e=>setForm({...form,cad_pro:e.target.value})}/></label>
        <label>Cultura do terceiro<input required maxLength={50} value={form.cultura} onChange={e=>setForm({...form,cultura:e.target.value})}/></label>
        <label>Safra do terceiro<input required maxLength={20} value={form.safra} onChange={e=>setForm({...form,safra:e.target.value})}/></label>
        <label>Armazém de terceiros<select required value={form.armazem||""} onChange={e=>setForm({...form,armazem:Number(e.target.value)})}><option value="">Selecione</option>{armazens.filter(a=>a.ativo).map(a=><option key={a.id} value={a.id}>{a.nome}</option>)}</select></label>
        <label>Data de entrada de terceiros<input required type="date" value={form.data_entrada} onChange={e=>setForm({...form,data_entrada:e.target.value})}/></label>
        <label>Peso líquido de terceiros (kg)<input required inputMode="decimal" value={form.peso_liquido_kg} onChange={e=>setForm({...form,peso_liquido_kg:e.target.value})}/></label>
        <label>Placa da entrada<input maxLength={7} value={form.placa} onChange={e=>setForm({...form,placa:e.target.value})}/></label>
        <label>Motorista da entrada<input maxLength={120} value={form.motorista} onChange={e=>setForm({...form,motorista:e.target.value})}/></label>
        <label>Documento da entrada<input maxLength={120} value={form.documento} onChange={e=>setForm({...form,documento:e.target.value})}/></label>
        <label>Observações da entrada<textarea maxLength={4000} value={form.observacoes} onChange={e=>setForm({...form,observacoes:e.target.value})}/></label>
        <BotaoAcao acao="cadastrar" disabled={ocupado} type="submit">Registrar entrada de terceiros</BotaoAcao>
      </FormularioValidado></details>
      <div className="painel-filtros"><label>Buscar produção de terceiros<input value={busca} onChange={e=>setBusca(e.target.value)}/></label><button type="button" disabled={ocupado} onClick={()=>void carregar()}>Atualizar terceiros</button></div>
      <p role="status">{visiveis.length} recebimento(s) · Saldo de terceiros nesta consulta: <strong>{formatarNumero(visiveis.reduce((s,i)=>s+Number(i.saldo_kg),0))} kg</strong></p>
      {visiveis.map(i=><article className="item" key={i.id}><div><h4>{i.depositante} · recebimento #{i.id}</h4><p>{i.propriedade_origem||"Origem não informada"} · CAD/PRO {i.cad_pro||"—"} · {i.cultura} · {i.safra} · {i.armazem_nome} · {dataBR(i.data_entrada)}</p><p>Recebido {formatarNumero(i.peso_liquido_kg)} kg · Saldo <strong>{formatarNumero(i.saldo_kg)} kg</strong></p>
        <div className="acoes"><ComprovanteLancamento rotulo="Imprimir entrada de terceiros" dados={{titulo:`Entrada de terceiros #${i.id}`,campos:[["Depositante",i.depositante],["Origem / CAD/PRO",`${i.propriedade_origem||"—"} / ${i.cad_pro||"—"}`],["Cultura / safra",`${i.cultura} / ${i.safra}`],["Armazém",i.armazem_nome],["Data",dataBR(i.data_entrada)],["Peso líquido recebido",`${formatarNumero(i.peso_liquido_kg)} kg`],["Saldo atual",`${formatarNumero(i.saldo_kg)} kg`],["Placa / motorista",`${i.placa||"—"} / ${i.motorista||"—"}`],["Documento",i.documento||"—"],["Situação",i.movimentos.some(m=>m.tipo==="entrada"&&m.estornado)?"Entrada estornada":"Registrada"],["Observações",i.observacoes||"—"]]}}/>
        {Number(i.saldo_kg)>0&&<BotaoAcao acao="cadastrar" disabled={ocupado} type="button" onClick={async()=>{if(await protecao.confirmarDescarte()){setAlvo(i.id);setSaida(novaSaida());setEstorno(null);protecao.marcarSalvo();}}}>Registrar saída de terceiros</BotaoAcao>}</div>
        <details><summary>Histórico de terceiros</summary>{i.movimentos.map(m=><div key={m.id}><p>#{m.id} · {m.tipo} · {dataBR(m.data_movimento)} · {formatarNumero(m.quantidade_kg)} kg · Saldo {formatarNumero(m.saldo_anterior_kg)} → {formatarNumero(m.saldo_posterior_kg)} kg · {m.criado_por_nome}{m.estornado?" · Estornado":""} · {m.destino} · {m.observacoes}</p>{m.tipo!=="estorno"&&!m.estornado&&<BotaoAcao acao="excluir" disabled={ocupado} type="button" className="secundario" onClick={async()=>{if(await protecao.confirmarDescarte()){setEstorno(m.id);setMotivo("");setAlvo(null);protecao.marcarSalvo();}}}>Estornar movimento #{m.id}</BotaoAcao>}</div>)}</details>
      </div></article>)}{!visiveis.length&&<p>Nenhuma entrada de terceiros encontrada.</p>}
      {alvo&&<FormularioValidado className="formulario" onSubmit={enviarSaida}><h4>Saída do recebimento #{alvo}</h4><label>Quantidade de terceiros a retirar (kg)<input required inputMode="decimal" value={saida.quantidade_kg} onChange={e=>setSaida({...saida,quantidade_kg:e.target.value})}/></label><label>Data de saída de terceiros<input required type="date" value={saida.data_movimento} onChange={e=>setSaida({...saida,data_movimento:e.target.value})}/></label><label>Destino da saída de terceiros<input required maxLength={160} value={saida.destino} onChange={e=>setSaida({...saida,destino:e.target.value})}/></label><label>Placa da saída<input maxLength={7} value={saida.placa} onChange={e=>setSaida({...saida,placa:e.target.value})}/></label><label>Motorista da saída<input maxLength={120} value={saida.motorista} onChange={e=>setSaida({...saida,motorista:e.target.value})}/></label><label>Documento da saída<input maxLength={120} value={saida.documento} onChange={e=>setSaida({...saida,documento:e.target.value})}/></label><label>Observações da saída<textarea maxLength={4000} value={saida.observacoes} onChange={e=>setSaida({...saida,observacoes:e.target.value})}/></label><div className="acoes"><BotaoAcao acao="cadastrar" type="submit" disabled={ocupado}>Confirmar saída de terceiros</BotaoAcao><button type="button" className="secundario" disabled={ocupado} onClick={async()=>{if(await protecao.confirmarDescarte()){setAlvo(null);setSaida(novaSaida());protecao.marcarSalvo();}}}>Cancelar saída</button></div></FormularioValidado>}
      {estorno&&<FormularioValidado className="formulario confirmacao-exclusao-carga" onSubmit={e=>{e.preventDefault();void operar(JSON.stringify(["estorno",estorno,motivo]),chave=>estornarTerceiro(estorno,motivo,hoje(),chave));}}><h4>Estornar movimento de terceiros #{estorno}</h4><p>O servidor confere o saldo. O registro original permanece no histórico.</p><label>Motivo do estorno<textarea required maxLength={500} value={motivo} onChange={e=>setMotivo(e.target.value)}/></label><div className="acoes"><BotaoAcao acao="excluir" className="perigo" type="submit" disabled={ocupado||!motivo.trim()}>Confirmar estorno</BotaoAcao><button type="button" className="secundario" disabled={ocupado} onClick={()=>{setEstorno(null);setMotivo("");}}>Cancelar estorno</button></div></FormularioValidado>}
    </>}
  </section>;
}
