import {VincularRecebimentos,ConciliacaoEstoque,DadosHistoricos} from "../../components/ConferenciaOperacional";
import { CadastroTerceiros, Fechamentos, PendenciasConferencia } from "../../components/GestaoConferencia";
import { useOperacaoConferida } from "../../components/OperacaoConferida";
import { listarCadastrosTerceiros, TerceiroCadastro } from "../../api/terceiros";
import { dadosRomaneioTerceiro } from "./romaneioTerceiro";
import { FormEvent, useContext, useEffect, useRef, useState } from "react";
import axios from "axios";
import { ArmazemGraos, CADPro } from "../../api/cargasColhidas";
import { Propriedade } from "../../api/propriedades";
import { EntradaTerceiro, NovaEntradaTerceiro, SaidaTerceiro, listarTerceiros, registrarEntradaTerceiro, registrarSaidaTerceiro, estornarTerceiro, previaTerceiro, editarEntradaTerceiro, excluirEntradaTerceiro } from "../../api/terceiros";
import FormularioValidado from "../../components/FormularioValidado";
import ComprovanteLancamento from "../../components/ComprovanteLancamento";
import { EquacaoPesagem, useConferirPesagem } from "../../components/ConferenciaPesagem";
import ResumoTerceiros from "./ResumoTerceiros";
import ExtratoTerceiro from "./ExtratoTerceiro";
import ConferenciaEstoque from "../../components/ConferenciaEstoque";
import { AcoesContext, autorizado, BotaoAcao } from "../../components/AcoesContext";
import { TransferenciaTerceiro, transferirTerceiro } from "../../api/terceiros";
import { formatarNumero } from "../../utils/numeros";
import { useAlteracoesNaoSalvas } from "../../components/AlteracoesNaoSalvas";
import { quantidadeContrato } from "../CadastrosAgricolas/ContratosComerciais";
import { consultarPainelSaldos } from "../../api/producaoSaldos";
const converterDecimalDigitado=(valor:string)=>{try{return quantidadeContrato(valor);}catch{return null;}};

const hoje=()=>{const data=new Date();return `${data.getFullYear()}-${String(data.getMonth()+1).padStart(2,"0")}-${String(data.getDate()).padStart(2,"0")}`;};
const novaEntrada=():NovaEntradaTerceiro=>({terceiro:null,depositante:"",cultura:"Soja",safra:"",armazem:0,peso_total_kg:null,tara_kg:null,peso_bruto_kg:"",umidade_percentual:"",impureza_percentual:"0",defeitos_percentual:"0",ph:null,ph_minimo:"0",desconto_ph_por_ponto:"0",data_entrada:hoje(),placa:"",motorista:"",documento:"",observacoes:""});
const novaSaida=():SaidaTerceiro=>({quantidade_kg:"",data_movimento:hoje(),destino:"",placa:"",motorista:"",documento:"",observacoes:""});
const dataBR=(data:string)=>data.split("-").reverse().join("/");
function erroTexto(falha:unknown){const dados=axios.isAxiosError(falha)?falha.response?.data:null;return dados?JSON.stringify(dados):"Não foi possível concluir. Confira a conexão e tente novamente.";}

export default function ProducaoTerceiros({armazens,propriedades=[],cadpros=[],atualizarArmazens,inicialmenteAberto=false,ativo=true}:{armazens:ArmazemGraos[];propriedades?:Propriedade[];cadpros?:CADPro[];atualizarArmazens:()=>Promise<void>;inicialmenteAberto?:boolean;ativo?:boolean}){
  const acesso=useContext(AcoesContext);
  const conferirPesagem=useConferirPesagem();
  const executarConferido=useOperacaoConferida();
  const [buscaAplicada,setBuscaAplicada]=useState('');
  const [situacao,setSituacao]=useState('ativos'),[situacaoAplicada,setSituacaoAplicada]=useState('ativos');
  const [saldoDestino,setSaldoDestino]=useState<number|null>(null),[erroDestino,setErroDestino]=useState('');
  const [paginaEntradas,setPaginaEntradas]=useState(1),[fimEntradas,setFimEntradas]=useState(false);
  async function carregarMais(){if(ocupado)return;setOcupado(true);try{const novos=await listarTerceiros(paginaEntradas+1,buscaAplicada,situacaoAplicada);setItens(atuais=>[...new Map([...atuais,...novos].map(i=>[i.id,i])).values()]);setPaginaEntradas(paginaEntradas+1);setFimEntradas(novos.length<25);}catch(f){setErro(erroTexto(f));}finally{setOcupado(false);}}
  const [cadastros,setCadastros]=useState<TerceiroCadastro[]>([]);
  async function carregarCadastros(){setCadastros(await listarCadastrosTerceiros());}
  const podeTransferir=acesso===null||autorizado(acesso.acesso,"transferencias","cadastrar");
  const podeEstornarTransferencia=acesso===null||autorizado(acesso.acesso,"transferencias","excluir");
  const [transferindo,setTransferindo]=useState<EntradaTerceiro|null>(null);
  const [transferencia,setTransferencia]=useState<TransferenciaTerceiro>({versao:1,propriedade:0,cad_pro:"",quantidade_kg:"",data_movimento:hoje(),documento:"",observacoes:""});
  const formularioTransferencia=useRef<HTMLFormElement>(null);
  useEffect(()=>{let vigente=true;setSaldoDestino(null);setErroDestino('');if(!transferindo||!transferencia.propriedade||!transferencia.cad_pro)return;
    void consultarPainelSaldos({propriedade:String(transferencia.propriedade),cad_pro:transferencia.cad_pro,armazem:String(transferindo.armazem),cultura:transferindo.cultura,safra:transferindo.safra}).then(p=>{if(vigente)setSaldoDestino(Number(p.resumo.saldo_disponivel_kg));}).catch(()=>{if(vigente)setErroDestino('Não foi possível consultar o saldo destinatário. Confira sua permissão de consulta em Produção e saldos.');});return()=>{vigente=false;};
  },[transferindo,transferencia.propriedade,transferencia.cad_pro]);
  const limparProtecao=useRef(false);
  useEffect(()=>{if(transferindo)formularioTransferencia.current?.scrollIntoView({block:"center",behavior:"smooth"});},[transferindo]);
  const [aberto,setAberto]=useState(inicialmenteAberto),[itens,setItens]=useState<EntradaTerceiro[]>([]),[form,setForm]=useState(novaEntrada),[saida,setSaida]=useState(novaSaida),[alvo,setAlvo]=useState<number|null>(null),[estorno,setEstorno]=useState<number|null>(null),[motivo,setMotivo]=useState(""),[busca,setBusca]=useState(""),[ocupado,setOcupado]=useState(false),[erro,setErro]=useState(""),[sucesso,setSucesso]=useState("");
  const [editando,setEditando]=useState<EntradaTerceiro|null>(null),[excluindo,setExcluindo]=useState<EntradaTerceiro|null>(null);
  const formularioEntrada=useRef<HTMLDetailsElement>(null);
  const confirmacao=useRef<HTMLDivElement>(null);
  useEffect(()=>{if(excluindo)confirmacao.current?.scrollIntoView({block:"center",behavior:"smooth"});},[excluindo]);
  const [previa,setPrevia]=useState<{peso_liquido_kg:string;desconto_total_percentual:string;desconto_total_kg:string}|null>(null),[erroPrevia,setErroPrevia]=useState("");
  useEffect(()=>{let ativa=true;setPrevia(null);setErroPrevia("");const bruto=(form.peso_total_kg!=null||form.tara_kg!=null?form.peso_bruto_kg:converterDecimalDigitado(form.peso_bruto_kg));if(!bruto||!form.umidade_percentual)return;
    const timer=setTimeout(()=>{void previaTerceiro({cultura:form.cultura,peso_total_kg:form.peso_total_kg,tara_kg:form.tara_kg,peso_bruto_kg:bruto,umidade_percentual:form.umidade_percentual,impureza_percentual:form.impureza_percentual,defeitos_percentual:form.defeitos_percentual,ph:form.cultura==="Trigo"?form.ph||null:null,ph_minimo:form.ph_minimo,desconto_ph_por_ponto:form.desconto_ph_por_ponto}).then(d=>{if(ativa)setPrevia(d);}).catch(f=>{if(ativa)setErroPrevia(erroTexto(f));});},250);
    return()=>{ativa=false;clearTimeout(timer);};
  },[form.cultura,form.peso_total_kg,form.tara_kg,form.peso_bruto_kg,form.umidade_percentual,form.impureza_percentual,form.defeitos_percentual,form.ph,form.ph_minimo,form.desconto_ph_por_ponto]);
  const trava=useRef(false),reenvio=useRef<{assinatura:string;chave:string}|null>(null);
  const protecao=useAlteracoesNaoSalvas({form,saida,motivo,transferencia},"Produção de terceiros");
  useEffect(()=>{if(limparProtecao.current){limparProtecao.current=false;protecao.marcarSalvo();}},[form,saida,motivo,transferencia]);
  async function carregar(){try{const novos=await listarTerceiros(1,busca,situacao);setItens(novos);setPaginaEntradas(1);setBuscaAplicada(busca);setSituacaoAplicada(situacao);setFimEntradas(novos.length<25);await carregarCadastros();setErro("");}catch(falha){setErro(erroTexto(falha));}}
  useEffect(()=>{if(inicialmenteAberto && ativo)void carregar();},[inicialmenteAberto,ativo,armazens]);
  function fecharTransferencia(){limparProtecao.current=true;setTransferindo(null);setTransferencia({versao:1,propriedade:0,cad_pro:"",quantidade_kg:"",data_movimento:hoje(),documento:"",observacoes:""});}
  async function operar(assinatura:string,acao:(chave:string)=>Promise<EntradaTerceiro>,conferir?:()=>Promise<boolean>){if(trava.current)return;trava.current=true;setOcupado(true);setErro("");setSucesso("");
    if(reenvio.current?.assinatura!==assinatura)reenvio.current={assinatura,chave:crypto.randomUUID()};
    try{if(conferir&&!(await conferir()))return;const salvo=await executarConferido(()=>acao(reenvio.current!.chave));setItens(atual=>[salvo,...atual.filter(i=>i.id!==salvo.id)]);setForm(novaEntrada());setEditando(null);setExcluindo(null);setSaida(novaSaida());setAlvo(null);setEstorno(null);setMotivo("");fecharTransferencia();reenvio.current=null;protecao.marcarSalvo();setSucesso("Movimentação de terceiros registrada. Produção própria preservada.");void atualizarArmazens().catch(()=>setErro("Registro salvo; atualize para conferir a ocupação do armazém."));}catch(falha){setErro(erroTexto(falha));}finally{trava.current=false;setOcupado(false);}}
  function enviarEntrada(e:FormEvent){e.preventDefault();const peso=(form.peso_total_kg!=null||form.tara_kg!=null?form.peso_bruto_kg:converterDecimalDigitado(form.peso_bruto_kg));if(!peso||Number(peso)<=0){setErro("Informe um peso bruto válido maior que zero.");return;}const dados={...form,peso_bruto_kg:peso,ph:form.cultura==="Trigo"?form.ph||null:null};void operar(JSON.stringify([editando?.id,editando?.versao,motivo,dados]),chave=>editando?editarEntradaTerceiro(editando.id,dados,editando.versao,motivo,chave):registrarEntradaTerceiro(dados,chave),()=>conferirPesagem({...dados,origem:"terceiro",...(editando?{excluir_id:editando.id}:{})}));}
  async function abrirEdicao(item:EntradaTerceiro){
    if(!(await protecao.confirmarDescarte()))return;
    fecharTransferencia();
    const bruto=item.peso_bruto_kg===null?"":item.peso_total_kg!=null?item.peso_bruto_kg:Number(item.peso_bruto_kg).toLocaleString("pt-BR",{maximumFractionDigits:3});
    setForm({...novaEntrada(),terceiro:item.terceiro??null,depositante:item.depositante,cultura:item.cultura,safra:item.safra,armazem:item.armazem,peso_total_kg:item.peso_total_kg??null,tara_kg:item.tara_kg??null,peso_bruto_kg:bruto,umidade_percentual:item.umidade_percentual??"",impureza_percentual:item.impureza_percentual??"0",defeitos_percentual:item.defeitos_percentual??"0",ph:item.ph,ph_minimo:item.regra_desconto_aplicada.parcelas?.ph?.minimo??"0",desconto_ph_por_ponto:item.regra_desconto_aplicada.parcelas?.ph?.desconto_por_ponto??"0",data_entrada:item.data_entrada,placa:item.placa,motorista:item.motorista,documento:item.documento,observacoes:item.observacoes});
    setEditando(item);setExcluindo(null);setMotivo("");setAlvo(null);setEstorno(null);if(formularioEntrada.current){formularioEntrada.current.open=true;formularioEntrada.current.scrollIntoView({block:"start",behavior:"smooth"});}protecao.marcarSalvo();
  }
  function enviarSaida(e:FormEvent){e.preventDefault();const peso=converterDecimalDigitado(saida.quantidade_kg);if(!peso||Number(peso)<=0||!alvo){setErro("Informe a quantidade da saída maior que zero.");return;}const dados={...saida,quantidade_kg:peso};void operar(JSON.stringify(["saida",alvo,dados]),chave=>registrarSaidaTerceiro(alvo,dados,chave));}
  async function abrirTransferencia(item:EntradaTerceiro){
    if(!(await protecao.confirmarDescarte()))return;
    limparProtecao.current=true;
    setAlvo(null);setEstorno(null);setExcluindo(null);setEditando(null);setForm(novaEntrada());setSaida(novaSaida());setMotivo("");
    setTransferindo(item);setTransferencia({versao:item.versao,propriedade:0,cad_pro:"",quantidade_kg:"",data_movimento:hoje(),documento:"",observacoes:""});protecao.marcarSalvo();
  }
  function enviarTransferencia(e:FormEvent){
    e.preventDefault();if(!transferindo)return;
    const peso=converterDecimalDigitado(transferencia.quantidade_kg);
    if(!peso||Number(peso)<=0||Number(peso)>Number(transferindo.saldo_kg)){setErro("Informe uma quantidade líquida maior que zero e dentro do saldo do terceiro.");return;}
    const dados={...transferencia,quantidade_kg:peso};
    void operar(JSON.stringify(["transferencia",transferindo.id,dados]),chave=>transferirTerceiro(transferindo.id,dados,chave));
  }
  const visiveis=itens;
  const quantidadeTransferir=Number(converterDecimalDigitado(transferencia.quantidade_kg)||0);
  const transferenciaValida=!!transferindo&&quantidadeTransferir>0&&quantidadeTransferir<=Number(transferindo.saldo_kg)&&!!transferencia.propriedade&&!!transferencia.cad_pro;
  return <section className="card nao-imprimir"><button className="secundario" type="button" aria-expanded={aberto} onClick={()=>{setAberto(!aberto);if(!aberto)void carregar();}}>Produção de terceiros · entradas e saldo separado</button>
    {aberto&&<><h3>Produção de terceiros</h3><p>O saldo ocupa o armazém e integra o estoque físico. Não entra na produção, área ou média das propriedades cadastradas. Os descontos seguem as mesmas regras das cargas próprias; o estoque recebe o peso líquido calculado.</p>
      {erro&&<p role="alert" className="erro">{erro}</p>}{sucesso&&<p role="status" className="sucesso">{sucesso}</p>}
      <CadastroTerceiros itens={cadastros} atualizar={carregarCadastros}/>
      <VincularRecebimentos cadastros={cadastros} atualizar={carregar}/><ConciliacaoEstoque armazens={armazens}/><Fechamentos armazens={armazens}/><PendenciasConferencia/>
      <details ref={formularioEntrada}><summary>{editando?`Editar entrada de terceiros #${editando.id}`:"Registrar entrada de terceiros"}</summary><FormularioValidado className="formulario terceiros-formulario" onSubmit={enviarEntrada}>
        <label>Cadastro do terceiro<select required={!editando} value={form.terceiro||""} onChange={e=>{const t=cadastros.find(t=>t.id===Number(e.target.value));setForm({...form,terceiro:t?.id??null,depositante:t?.nome||form.depositante});}}><option value="">{editando?"Sem vínculo: recebimento antigo":"Selecione um cadastro"}</option>{cadastros.filter(t=>t.ativo||t.id===form.terceiro).map(t=><option key={t.id} value={t.id}>{t.codigo} · {t.nome}</option>)}</select></label>
        <label>Nome do terceiro<input disabled={!!form.terceiro} required maxLength={160} value={form.depositante} onChange={e=>setForm({...form,depositante:e.target.value})}/></label>
        <label>Cultura<select value={form.cultura} onChange={e=>setForm({...form,cultura:e.target.value})}>{["Soja","Milho","Trigo"].map(c=><option key={c}>{c}</option>)}</select></label>
        <label>Safra do terceiro<input required maxLength={20} value={form.safra} onChange={e=>setForm({...form,safra:e.target.value})}/></label>
        <label>Armazém de terceiros<select required disabled={!!editando} value={form.armazem||""} onChange={e=>setForm({...form,armazem:Number(e.target.value)})}><option value="">Selecione</option>{armazens.filter(a=>a.ativo).map(a=><option key={a.id} value={a.id}>{a.nome}</option>)}</select></label>
        <label>Data de entrada de terceiros<input required type="date" value={form.data_entrada} onChange={e=>setForm({...form,data_entrada:e.target.value})}/></label>
        <label>Peso total (kg)<input type="number" min="0.001" step="0.001" value={form.peso_total_kg??""} onChange={e=>{const total=e.target.value;setForm({...form,peso_total_kg:total||null,peso_bruto_kg:total&&form.tara_kg!=null?(Number(total)-Number(form.tara_kg)).toFixed(3):form.peso_bruto_kg});}}/></label>
        <label>Tara (kg)<input type="number" min="0" step="0.001" value={form.tara_kg??""} onChange={e=>{const tara=e.target.value;setForm({...form,tara_kg:tara||null,peso_bruto_kg:tara&&form.peso_total_kg!=null?(Number(form.peso_total_kg)-Number(tara)).toFixed(3):form.peso_bruto_kg});}}/></label>
        <label>Peso bruto do produto (kg)<input required inputMode="decimal" readOnly={form.peso_total_kg!=null||form.tara_kg!=null} value={form.peso_bruto_kg} onChange={e=>setForm({...form,peso_bruto_kg:e.target.value})}/></label>
        {([ ["umidade_percentual","Umidade (%)"], ["impureza_percentual","Impureza (%)"], ["defeitos_percentual","Avariados (%)"], ["ph","PH"] ] as const).filter(([campo])=>campo!=="ph"||form.cultura==="Trigo").map(([campo,rotulo])=><label key={campo}>{rotulo}<input required={campo!=="ph"} type="number" min="0" max="100" step="0.001" value={form[campo]??""} onChange={e=>setForm({...form,[campo]:e.target.value})}/></label>)}
        <div className="terceiros-resumo" role="status">{previa?<><span>Desconto <strong>{formatarNumero(previa.desconto_total_percentual)}% · {formatarNumero(previa.desconto_total_kg)} kg</strong></span><span>Peso líquido <strong>{formatarNumero(previa.peso_liquido_kg)} kg</strong></span></>:<span>{erroPrevia||"Preencha peso e classificação para conferir o líquido antes de registrar."}</span>}</div>
        {previa&&<EquacaoPesagem dados={{...form,...previa,peso_bruto_kg:form.peso_total_kg!=null?form.peso_bruto_kg:converterDecimalDigitado(form.peso_bruto_kg)||"0"}}/>}
        <label>Placa da entrada<input maxLength={7} value={form.placa} onChange={e=>setForm({...form,placa:e.target.value})}/></label>
        <label>Motorista da entrada<input maxLength={120} value={form.motorista} onChange={e=>setForm({...form,motorista:e.target.value})}/></label>
        <label>Documento da entrada<input maxLength={120} value={form.documento} onChange={e=>setForm({...form,documento:e.target.value})}/></label>
        <label>Observações da entrada<textarea maxLength={4000} value={form.observacoes} onChange={e=>setForm({...form,observacoes:e.target.value})}/></label>
        {editando&&<label className="terceiros-linha-inteira">Motivo da edição<textarea required maxLength={500} value={motivo} onChange={e=>setMotivo(e.target.value)}/></label>}
        <div className="acoes terceiros-linha-inteira"><BotaoAcao acao={editando?"editar":"cadastrar"} disabled={ocupado} type="submit">{editando?"Salvar edição":"Registrar entrada de terceiros"}</BotaoAcao>{editando&&<button type="button" className="secundario" disabled={ocupado} onClick={async()=>{if(await protecao.confirmarDescarte()){setEditando(null);setForm(novaEntrada());setMotivo("");protecao.marcarSalvo();}}}>Cancelar edição</button>}</div>
      </FormularioValidado></details>
      <ResumoTerceiros entradas={itens} ativo={aberto&&ativo}/>
      <ExtratoTerceiro entradas={itens} ativo={aberto&&ativo}/>
      <ConferenciaEstoque armazens={armazens}/>
      <div className="painel-filtros"><label>Situação dos recebimentos<select value={situacao} onChange={e=>setSituacao(e.target.value)}><option value="ativos">Ativos</option><option value="cancelados">Cancelados</option><option value="esgotados">Saldo esgotado</option><option value="">Todos</option></select></label><label>Buscar produção de terceiros<input value={busca} onChange={e=>setBusca(e.target.value)}/></label><button type="button" disabled={ocupado} onClick={()=>void carregar()}>Atualizar terceiros</button></div>
      <p>O filtro inicial mostra recebimentos ativos. Selecione Cancelados ou Todos e clique em Atualizar terceiros para consultar o histórico.</p>{!visiveis.length&&<p role="status">Nenhum recebimento encontrado para os filtros aplicados.</p>}<p role="status">{visiveis.length} recebimento(s) · Saldo de terceiros nesta consulta: <strong>{formatarNumero(visiveis.reduce((s,i)=>s+Number(i.saldo_kg),0))} kg</strong></p>
      {visiveis.map(i=><article className="item terceiro-recebimento" key={i.id}><div><h4>{i.depositante} · recebimento #{i.id}</h4><p><strong>Status: {i.movimentos.some(m=>m.tipo==="entrada"&&m.estornado)?"Cancelado":Number(i.saldo_kg)>0?"Ativo":"Saldo esgotado"}</strong></p><p>{i.cultura} · {i.safra} · {i.armazem_nome} · {dataBR(i.data_entrada)}</p><p>Peso total {i.peso_total_kg==null?"Não informado":`${formatarNumero(i.peso_total_kg)} kg`} · Tara {i.tara_kg==null?"Não informada":`${formatarNumero(i.tara_kg)} kg`} · {i.peso_bruto_kg!==null&&<>Bruto do produto {formatarNumero(i.peso_bruto_kg)} kg · Desconto {formatarNumero(i.desconto_total_percentual||"0")}% · </>}Líquido {formatarNumero(i.peso_liquido_kg)} kg · Saldo <strong>{formatarNumero(i.saldo_kg)} kg</strong></p>
        <div className="acoes"><ComprovanteLancamento duasVias rotulo="Romaneio" downloadRomaneio={{terceiroId:i.id}} dados={dadosRomaneioTerceiro(i)}/>
        {!i.movimentos.some(m=>m.tipo==="entrada"&&m.estornado)&&<><BotaoAcao acao="editar" disabled={ocupado} type="button" onClick={()=>void abrirEdicao(i)}>Editar entrada</BotaoAcao><BotaoAcao acao="excluir" className="perigo" disabled={ocupado} type="button" onClick={async()=>{if(await protecao.confirmarDescarte()){fecharTransferencia();setExcluindo(i);setEditando(null);setForm(novaEntrada());setMotivo("");setAlvo(null);setEstorno(null);protecao.marcarSalvo();}}}>Excluir entrada</BotaoAcao></>}
        {Number(i.saldo_kg)>0&&<><BotaoAcao acao="cadastrar" disabled={ocupado} type="button" onClick={async()=>{if(await protecao.confirmarDescarte()){fecharTransferencia();setAlvo(i.id);setSaida(novaSaida());setEstorno(null);setEditando(null);setExcluindo(null);setForm(novaEntrada());setMotivo("");protecao.marcarSalvo();}}}>Registrar saída de terceiros</BotaoAcao></>}<span className="acao-com-aviso"><button className="secundario" disabled={ocupado||!podeTransferir||(acesso!==null&&!autorizado(acesso.acesso,"cargas","cadastrar"))||Number(i.saldo_kg)<=0||i.movimentos.some(m=>m.tipo==="entrada"&&m.estornado)} type="button" onClick={()=>void abrirTransferencia(i)}>Transferir para outra propriedade</button>{(i.movimentos.some(m=>m.tipo==="entrada"&&m.estornado)||Number(i.saldo_kg)<=0||!podeTransferir||(acesso!==null&&!autorizado(acesso.acesso,"cargas","cadastrar")))&&<small>{i.movimentos.some(m=>m.tipo==="entrada"&&m.estornado)?"Recebimento cancelado: transferência bloqueada.":Number(i.saldo_kg)<=0?"Sem saldo disponível para transferir.":"Sem permissão para cadastrar cargas e transferências."}</small>}</span></div>
        <details><summary aria-label="Histórico de terceiros">Histórico</summary>{i.movimentos.map(m=><div key={m.id}><p>#{m.id} · {m.tipo==="transferencia"?"Transferência para propriedade":m.tipo} · {dataBR(m.data_movimento)} · {formatarNumero(m.quantidade_kg)} kg · Saldo {formatarNumero(m.saldo_anterior_kg)} → {formatarNumero(m.saldo_posterior_kg)} kg · {m.criado_por_nome}{m.estornado?" · Estornado":""} · {m.destino} · {m.observacoes}</p>{m.tipo==="edicao"&&<details><summary>Dados originais e corrigidos</summary><DadosHistoricos antes={m.snapshot_antes} depois={m.snapshot_depois}/></details>}{m.tipo==="transferencia"&&<ComprovanteLancamento duasVias rotulo="Comprovante da transferência" downloadRomaneio={{transferenciaTerceiroId:m.id}} dados={{titulo:`Transferência de terceiros #${m.id}`,campos:[["Terceiro de origem",String(m.snapshot_depois?.depositante||i.depositante)],["Destino",m.destino],["Produto / safra",`${i.cultura} / ${i.safra}`],["Data",dataBR(m.data_movimento)],["Quantidade",`${formatarNumero(m.quantidade_kg)} kg`],["Saldo do terceiro antes",`${formatarNumero(m.saldo_anterior_kg)} kg`],["Saldo do terceiro após",`${formatarNumero(m.saldo_posterior_kg)} kg`],["Motivo",m.observacoes],["Responsável",m.criado_por_nome],["Situação",m.estornado?"Estornada":"Registrada"],["Contabilidade","Somente estoque, sem produção ou produtividade."]]}}/>}{m.tipo==="saida"&&<ComprovanteLancamento duasVias rotulo="Comprovante de retirada" downloadRomaneio={{retiradaTerceiroId:m.id}} dados={{titulo:`Retirada de terceiros #${m.id}`,campos:[["Terceiro",String(m.snapshot_depois?.depositante||i.depositante)],["Data",dataBR(m.data_movimento)],["Produto / safra",`${String(m.snapshot_depois?.cultura||i.cultura)} / ${String(m.snapshot_depois?.safra||i.safra)}`],["Quantidade",`${formatarNumero(m.quantidade_kg)} kg`],["Destino",m.destino],["Motorista",m.motorista],["Placa",m.placa],["Documento",m.documento],["Saldo após retirada",`${formatarNumero(m.saldo_posterior_kg)} kg`],["Situação",m.estornado?"Estornada":"Registrada"],["Responsável",m.criado_por_nome],["Armazém",String(m.snapshot_depois?.armazem_nome||i.armazem_nome)],["Observações",m.observacoes],["Assinatura motorista","________________________"],["Assinatura do responsável","________________________"]]}}/>}{m.tipo!=="estorno"&&m.tipo!=="edicao"&&!m.estornado&&(!m.movimentacao_saldo||podeEstornarTransferencia)&&<BotaoAcao acao="excluir" disabled={ocupado} type="button" className="secundario" onClick={async()=>{if(await protecao.confirmarDescarte()){fecharTransferencia();setEstorno(m.id);setMotivo("");setAlvo(null);setEditando(null);setExcluindo(null);setForm(novaEntrada());protecao.marcarSalvo();}}}>Estornar movimento #{m.id}</BotaoAcao>}</div>)}</details>
      </div></article>)}{!fimEntradas&&<button type="button" className="secundario" disabled={ocupado} onClick={()=>void carregarMais()}>Carregar mais recebimentos</button>}<p>Pesquisa no servidor. Clique em Atualizar terceiros após digitar; os resultados incluem registros ainda não carregados. O resumo consulta os totais no servidor.</p>{!visiveis.length&&<p>Nenhuma entrada de terceiros encontrada.</p>}
      {alvo&&<FormularioValidado className="formulario" onSubmit={enviarSaida}><h4>Saída do recebimento #{alvo}</h4><label>Quantidade de terceiros a retirar (kg)<input required inputMode="decimal" value={saida.quantidade_kg} onChange={e=>setSaida({...saida,quantidade_kg:e.target.value})}/></label><label>Data de saída de terceiros<input required type="date" value={saida.data_movimento} onChange={e=>setSaida({...saida,data_movimento:e.target.value})}/></label><label>Destino da saída de terceiros<input required maxLength={160} value={saida.destino} onChange={e=>setSaida({...saida,destino:e.target.value})}/></label><label>Placa da saída<input maxLength={7} value={saida.placa} onChange={e=>setSaida({...saida,placa:e.target.value})}/></label><label>Motorista da saída<input maxLength={120} value={saida.motorista} onChange={e=>setSaida({...saida,motorista:e.target.value})}/></label><label>Documento da saída<input maxLength={120} value={saida.documento} onChange={e=>setSaida({...saida,documento:e.target.value})}/></label><label>Observações da saída<textarea maxLength={4000} value={saida.observacoes} onChange={e=>setSaida({...saida,observacoes:e.target.value})}/></label><div className="acoes"><BotaoAcao acao="cadastrar" type="submit" disabled={ocupado}>Confirmar saída de terceiros</BotaoAcao><button type="button" className="secundario" disabled={ocupado} onClick={async()=>{if(await protecao.confirmarDescarte()){setAlvo(null);setSaida(novaSaida());protecao.marcarSalvo();}}}>Cancelar saída</button></div></FormularioValidado>}
      {excluindo&&<div ref={confirmacao}><FormularioValidado className="formulario confirmacao-exclusao-carga" onSubmit={e=>{e.preventDefault();void operar(JSON.stringify(["excluir",excluindo.id,excluindo.versao,motivo]),chave=>excluirEntradaTerceiro(excluindo.id,excluindo.versao,motivo,hoje(),chave));}}><h4>Excluir entrada de {excluindo.depositante}</h4><p>A exclusão estorna {formatarNumero(excluindo.peso_liquido_kg)} kg e preserva o histórico. Retiradas ativas devem ser estornadas antes.</p><label>Motivo da exclusão<textarea required maxLength={500} value={motivo} onChange={e=>setMotivo(e.target.value)}/></label><div className="acoes"><BotaoAcao acao="excluir" className="perigo" type="submit" disabled={ocupado||!motivo.trim()}>Confirmar exclusão</BotaoAcao><button type="button" className="secundario" disabled={ocupado} onClick={()=>{setExcluindo(null);setMotivo("");}}>Cancelar exclusão</button></div></FormularioValidado></div>}
      {transferindo&&podeTransferir&&<FormularioValidado ref={formularioTransferencia} className="formulario terceiros-formulario" onSubmit={enviarTransferencia}>
        <h4 className="terceiros-linha-inteira">Transferir saldo de {transferindo.depositante} para outra propriedade</h4>
        <p className="terceiros-linha-inteira">Saldo disponível: <strong>{formatarNumero(transferindo.saldo_kg)} kg</strong> · {transferindo.cultura} · {transferindo.safra} · {transferindo.armazem_nome}. Selecione a propriedade destinatária e seu CAD/PRO ativo. A transferência usa o peso líquido e mantém o mesmo armazém. O recebimento entra somente no estoque da destinatária, sem somar produção colhida, área, média ou produtividade.</p>
        <label>Propriedade de destino<select required value={transferencia.propriedade||""} onChange={e=>setTransferencia({...transferencia,propriedade:Number(e.target.value),cad_pro:""})}><option value="">Selecione</option>{propriedades.filter(p=>cadpros.some(c=>c.ativo&&c.propriedades.includes(p.id))).map(p=><option key={p.id} value={p.id}>{p.nome}</option>)}</select></label>
        <label>CAD/PRO de destino<select required disabled={!transferencia.propriedade} value={transferencia.cad_pro} onChange={e=>setTransferencia({...transferencia,cad_pro:e.target.value})}><option value="">Selecione</option>{cadpros.filter(c=>c.ativo&&c.propriedades.includes(transferencia.propriedade)).map(c=><option key={c.id} value={c.id}>{c.codigo} · {c.descricao}</option>)}</select></label>
        <label>Quantidade líquida a transferir (kg)<input required inputMode="decimal" value={transferencia.quantidade_kg} onChange={e=>setTransferencia({...transferencia,quantidade_kg:e.target.value})}/></label>
        <label>Data da transferência<input required type="date" value={transferencia.data_movimento} onChange={e=>setTransferencia({...transferencia,data_movimento:e.target.value})}/></label>
        <label>Documento da transferência<input maxLength={120} value={transferencia.documento} onChange={e=>setTransferencia({...transferencia,documento:e.target.value})}/></label>
        <label>Motivo da transferência<textarea required maxLength={4000} value={transferencia.observacoes} onChange={e=>setTransferencia({...transferencia,observacoes:e.target.value})}/></label>
        <section className="card terceiros-linha-inteira" aria-label="Prévia da transferência"><h4>Confira antes de confirmar</h4><p>Origem: {transferindo.depositante} · recebimento #{transferindo.id}</p><p>Destinatária: {propriedades.find(p=>p.id===transferencia.propriedade)?.nome||"Selecione a propriedade"} · CAD/PRO {cadpros.find(c=>c.id===transferencia.cad_pro)?.codigo||"Selecione"}</p><p>Quantidade: {formatarNumero(quantidadeTransferir)} kg · Saldo do terceiro após: {transferenciaValida?formatarNumero(Number(transferindo.saldo_kg)-quantidadeTransferir):"Informe uma quantidade válida"} kg</p><p>Disponível da destinatária: {saldoDestino===null?(erroDestino||"Selecione o destino para consultar."):`${formatarNumero(saldoDestino)} kg → ${formatarNumero(saldoDestino+quantidadeTransferir)} kg`}</p><small>Prévia nas dimensões deste produto, safra e armazém. O servidor valida os saldos ao salvar. Não altera produção, área, média ou produtividade.</small></section>
        <div className="acoes terceiros-linha-inteira"><BotaoAcao acao="cadastrar" disabled={ocupado||!transferenciaValida} type="submit">Confirmar transferência para outra propriedade</BotaoAcao><button className="secundario" type="button" disabled={ocupado} onClick={async()=>{if(await protecao.confirmarDescarte()){fecharTransferencia();protecao.marcarSalvo();}}}>Cancelar transferência</button></div>
      </FormularioValidado>}
      {estorno&&<FormularioValidado className="formulario confirmacao-exclusao-carga" onSubmit={e=>{e.preventDefault();void operar(JSON.stringify(["estorno",estorno,motivo]),chave=>estornarTerceiro(estorno,motivo,hoje(),chave));}}><h4>Estornar movimento de terceiros #{estorno}</h4><p>O servidor confere o saldo. O registro original permanece no histórico. Transferências devolvem o líquido ao terceiro e descontam o mesmo valor do CAD/PRO, se houver saldo livre.</p><label>Motivo do estorno<textarea required maxLength={500} value={motivo} onChange={e=>setMotivo(e.target.value)}/></label><div className="acoes"><BotaoAcao acao="excluir" className="perigo" type="submit" disabled={ocupado||!motivo.trim()}>Confirmar estorno</BotaoAcao><button type="button" className="secundario" disabled={ocupado} onClick={()=>{setEstorno(null);setMotivo("");}}>Cancelar estorno</button></div></FormularioValidado>}
    </>}
  </section>;
}
