# Generated by Django 5.1.15 on 2026-07-24 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propriedades', '0002_propriedade_arquivo_kml_propriedade_proprietario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrevisaoClima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('temperatura_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperatura_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('chuva_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('umidade', models.IntegerField(blank=True, null=True)),
                ('vento_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('condicao', models.CharField(blank=True, max_length=100)),
                ('alerta_agricola', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previsoes_clima', to='propriedades.propriedade')),
            ],
        ),
    ]
