# Generated by Django 5.1.15 on 2026-07-26 01:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0001_initial'),
        ('propriedades', '0003_propriedade_area_calculada_hectares_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='previsaoclima',
            options={'ordering': ('data', 'propriedade_id')},
        ),
        migrations.AddField(
            model_name='previsaoclima',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='previsaoclima',
            name='codigo_tempo',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='previsaoclima',
            name='fonte',
            field=models.CharField(default='Open-Meteo', max_length=50),
        ),
        migrations.AddField(
            model_name='previsaoclima',
            name='probabilidade_chuva',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='previsaoclima',
            name='propriedade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='previsoes_clima', to='propriedades.propriedade'),
        ),
        migrations.AlterField(
            model_name='previsaoclima',
            name='umidade',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddConstraint(
            model_name='previsaoclima',
            constraint=models.UniqueConstraint(fields=('propriedade', 'data'), name='clima_previsao_unica_por_propriedade_data'),
        ),
        migrations.AddConstraint(
            model_name='previsaoclima',
            constraint=models.CheckConstraint(condition=models.Q(('chuva_mm__gte', 0), ('chuva_mm__isnull', True), _connector='OR'), name='clima_chuva_nao_negativa'),
        ),
        migrations.AddConstraint(
            model_name='previsaoclima',
            constraint=models.CheckConstraint(condition=models.Q(('vento_kmh__gte', 0), ('vento_kmh__isnull', True), _connector='OR'), name='clima_vento_nao_negativo'),
        ),
    ]
