import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clima", "0002_alter_previsaoclima_options_and_more"),
        ("talhoes", "0007_talhao_area_calculada_hectares"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoClima",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ativo", models.BooleanField(default=True)),
                ("frequencia_minutos", models.PositiveIntegerField(default=180, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(1440)])),
                ("limite_chuva_forte_mm", models.DecimalField(decimal_places=2, default=50, max_digits=7)),
                ("limite_geada_c", models.DecimalField(decimal_places=2, default=3, max_digits=5)),
                ("limite_calor_c", models.DecimalField(decimal_places=2, default=35, max_digits=5)),
                ("limite_frio_c", models.DecimalField(decimal_places=2, default=8, max_digits=5)),
                ("limite_vento_forte_kmh", models.DecimalField(decimal_places=2, default=40, max_digits=6)),
                ("limite_umidade_alta", models.PositiveSmallIntegerField(default=90, validators=[django.core.validators.MaxValueValidator(100)])),
                ("limite_umidade_baixa", models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MaxValueValidator(100)])),
                ("limite_deriva_vento_kmh", models.DecimalField(decimal_places=2, default=15, max_digits=6)),
                ("limite_lavagem_chuva_mm", models.DecimalField(decimal_places=2, default=5, max_digits=6)),
                ("dias_sem_chuva_alerta", models.PositiveSmallIntegerField(default=7)),
                ("ultima_tentativa", models.DateTimeField(blank=True, null=True)),
                ("ultima_atualizacao", models.DateTimeField(blank=True, null=True)),
                ("proxima_atualizacao", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(choices=[("pendente", "Pendente"), ("atualizando", "Atualizando"), ("atualizado", "Atualizado"), ("erro", "Erro"), ("sem_localizacao", "Sem localização")], default="pendente", max_length=20)),
                ("erro_ultima_atualizacao", models.CharField(blank=True, max_length=240)),
                ("falhas_consecutivas", models.PositiveIntegerField(default=0)),
                ("total_chamadas", models.PositiveBigIntegerField(default=0)),
                ("origem_coordenadas", models.CharField(blank=True, max_length=24)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("propriedade", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="configuracao_clima", to="propriedades.propriedade")),
            ],
            options={"ordering": ("propriedade__nome",)},
        ),
        migrations.AddField(model_name="previsaoclima", name="sensacao_min", field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
        migrations.AddField(model_name="previsaoclima", name="sensacao_max", field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
        migrations.AddField(model_name="previsaoclima", name="rajada_vento_kmh", field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
        migrations.AddField(model_name="previsaoclima", name="direcao_vento", field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(360)])),
        migrations.AddField(model_name="previsaoclima", name="pressao_hpa", field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
        migrations.AddField(model_name="previsaoclima", name="cobertura_nuvens", field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)])),
        migrations.AddField(model_name="previsaoclima", name="radiacao_solar_mj", field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
        migrations.AddField(model_name="previsaoclima", name="ponto_orvalho", field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
        migrations.AddField(model_name="previsaoclima", name="evapotranspiracao_mm", field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
        migrations.AddField(model_name="previsaoclima", name="nascer_sol", field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name="previsaoclima", name="por_sol", field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name="previsaoclima", name="condicao_pulverizacao", field=models.CharField(blank=True, max_length=16)),
        migrations.AddField(model_name="previsaoclima", name="condicao_colheita", field=models.CharField(blank=True, max_length=16)),
        migrations.AddField(model_name="previsaoclima", name="risco_deriva", field=models.BooleanField(default=False)),
        migrations.AddField(model_name="previsaoclima", name="risco_lavagem", field=models.BooleanField(default=False)),
        migrations.AddField(model_name="previsaoclima", name="risco_estresse_hidrico", field=models.BooleanField(default=False)),
        migrations.AlterField(model_name="previsaoclima", name="fonte", field=models.CharField(default="Open-Meteo", max_length=80)),
        migrations.CreateModel(
            name="PrevisaoHoraria",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("data_hora", models.DateTimeField()),
                ("temperatura", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("sensacao_termica", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("umidade", models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ("precipitacao_mm", models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ("probabilidade_chuva", models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ("vento_kmh", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("direcao_vento", models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(360)])),
                ("rajada_vento_kmh", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("pressao_hpa", models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ("cobertura_nuvens", models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ("radiacao_solar", models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ("ponto_orvalho", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("evapotranspiracao_mm", models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ("codigo_tempo", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("condicao", models.CharField(blank=True, max_length=100)),
                ("condicao_pulverizacao", models.CharField(blank=True, max_length=16)),
                ("condicao_colheita", models.CharField(blank=True, max_length=16)),
                ("risco_deriva", models.BooleanField(default=False)),
                ("risco_lavagem", models.BooleanField(default=False)),
                ("fonte", models.CharField(default="Open-Meteo", max_length=80)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("propriedade", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="previsoes_clima_horarias", to="propriedades.propriedade")),
            ],
            options={"ordering": ("data_hora",)},
        ),
        migrations.CreateModel(
            name="AlertaClimatico",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("chave", models.CharField(max_length=160)),
                ("tipo", models.CharField(max_length=40)),
                ("nivel", models.CharField(choices=[("informativo", "Informativo"), ("atencao", "Atenção"), ("critico", "Crítico")], max_length=12)),
                ("titulo", models.CharField(max_length=160)),
                ("descricao", models.TextField()),
                ("inicio", models.DateTimeField()),
                ("fim", models.DateTimeField(blank=True, null=True)),
                ("ativo", models.BooleanField(default=True)),
                ("lido_em", models.DateTimeField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("propriedade", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="alertas_climaticos", to="propriedades.propriedade")),
                ("talhao", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="alertas_climaticos", to="talhoes.talhao")),
            ],
            options={"ordering": ("-inicio", "-id")},
        ),
        migrations.CreateModel(
            name="AtualizacaoClima",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("iniciada_em", models.DateTimeField(default=django.utils.timezone.now)),
                ("finalizada_em", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(choices=[("sucesso", "Sucesso"), ("erro", "Erro"), ("cache", "Cache"), ("ignorada", "Ignorada")], max_length=10)),
                ("origem_coordenadas", models.CharField(blank=True, max_length=24)),
                ("chamadas_provedor", models.PositiveSmallIntegerField(default=0)),
                ("previsoes_diarias", models.PositiveSmallIntegerField(default=0)),
                ("previsoes_horarias", models.PositiveSmallIntegerField(default=0)),
                ("tipo_erro", models.CharField(blank=True, max_length=80)),
                ("mensagem", models.CharField(blank=True, max_length=240)),
                ("propriedade", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="atualizacoes_clima", to="propriedades.propriedade")),
            ],
            options={"ordering": ("-iniciada_em", "-id")},
        ),
        migrations.AddConstraint(model_name="previsaohoraria", constraint=models.UniqueConstraint(fields=("propriedade", "data_hora"), name="clima_horaria_unica_propriedade_hora")),
        migrations.AddIndex(model_name="previsaohoraria", index=models.Index(fields=["propriedade", "data_hora"], name="clima_prop_hora_idx")),
        migrations.AddConstraint(model_name="alertaclimatico", constraint=models.UniqueConstraint(fields=("propriedade", "chave"), name="clima_alerta_chave_unica_propriedade")),
        migrations.AddIndex(model_name="alertaclimatico", index=models.Index(fields=["propriedade", "ativo", "inicio"], name="clima_alerta_ativo_idx")),
        migrations.AddIndex(model_name="atualizacaoclima", index=models.Index(fields=["propriedade", "iniciada_em"], name="clima_atualizacao_idx")),
    ]
