# Generated by Django 5.1.15 on 2026-07-26 03:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producao', '0001_initial'),
        ('propriedades', '0003_propriedade_area_calculada_hectares_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(max_length=80, unique=True)),
                ('tipo', models.CharField(choices=[('trator', 'Trator'), ('colheitadeira', 'Colheitadeira'), ('pulverizador', 'Pulverizador'), ('implemento', 'Implemento'), ('caminhao', 'Caminhão'), ('outro', 'Outro')], max_length=20)),
                ('marca', models.CharField(blank=True, max_length=80)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('ano', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('manutencao', 'Em manutenção'), ('inativa', 'Inativa')], default='ativa', max_length=12)),
                ('horimetro_atual', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('propriedade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maquinas', to='propriedades.propriedade')),
            ],
            options={
                'ordering': ('identificacao',),
            },
        ),
        migrations.CreateModel(
            name='ManutencaoMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=220)),
                ('data_prevista', models.DateField()),
                ('horimetro_previsto', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='agendada', max_length=10)),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('horimetro_realizado', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True)),
                ('custo', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manutencoes', to='maquinas.maquina')),
            ],
            options={
                'ordering': ('data_prevista', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AbastecimentoMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('litros', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('horimetro', models.DecimalField(decimal_places=1, max_digits=12)),
                ('documento', models.CharField(blank=True, max_length=80)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abastecimentos', to='maquinas.maquina')),
            ],
            options={
                'ordering': ('-data', '-id'),
            },
        ),
        migrations.CreateModel(
            name='UsoMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operador', models.CharField(blank=True, max_length=120)),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('horimetro_inicial', models.DecimalField(decimal_places=1, max_digits=12)),
                ('horimetro_final', models.DecimalField(decimal_places=1, max_digits=12)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos', to='maquinas.maquina')),
                ('operacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maquinas_utilizadas', to='producao.operacaoagricola')),
            ],
            options={
                'ordering': ('-data', '-id'),
            },
        ),
    ]
