# Generated by Django 5.1.15 on 2026-10-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acessousuario',
            name='permissoes',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
