# Generated by Django 5.1.15 on 2026-08-06 22:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propriedades', '0003_propriedade_area_calculada_hectares_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CADPro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50)),
                ('codigo_normalizado', models.CharField(editable=False, max_length=50, unique=True)),
                ('descricao', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CAD/PRO',
                'verbose_name_plural': 'CAD/PROs',
                'ordering': ('codigo_normalizado', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CADProPropriedade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cad_pro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_propriedades', to='cadpro.cadpro')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_cadpro', to='propriedades.propriedade')),
            ],
            options={
                'verbose_name': 'vínculo CAD/PRO e propriedade',
                'verbose_name_plural': 'vínculos CAD/PRO e propriedades',
                'ordering': ('propriedade__nome', 'id'),
                'constraints': [models.UniqueConstraint(fields=('cad_pro', 'propriedade'), name='cadpro_cad_pro_propriedade_unico')],
            },
        ),
    ]
