# Generated by Django 5.1.15 on 2026-07-30 09:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propriedades', '0003_propriedade_area_calculada_hectares_and_more'),
        ('talhoes', '0007_talhao_area_calculada_hectares'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmazemGraos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('capacidade_kg', models.DecimalField(decimal_places=3, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='armazens_graos', to='propriedades.propriedade')),
            ],
            options={
                'verbose_name': 'armazém de grãos',
                'verbose_name_plural': 'armazéns de grãos',
                'ordering': ('nome', 'id'),
            },
        ),
        migrations.CreateModel(
            name='LoteGraos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('cultura', models.CharField(max_length=50)),
                ('safra', models.CharField(max_length=20)),
                ('umidade_percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('impureza_percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('ativo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('armazem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='graos.armazemgraos')),
                ('talhao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes_graos', to='talhoes.talhao')),
            ],
            options={
                'verbose_name': 'lote de grãos',
                'verbose_name_plural': 'lotes de grãos',
                'ordering': ('safra', 'cultura', 'codigo', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoGraos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=8)),
                ('quantidade_kg', models.DecimalField(decimal_places=3, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('data_movimento', models.DateField(default=django.utils.timezone.localdate)),
                ('referencia_externa', models.CharField(blank=True, max_length=120)),
                ('chave_idempotencia', models.CharField(blank=True, editable=False, max_length=160, null=True, unique=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_graos', to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='graos.lotegraos')),
            ],
            options={
                'verbose_name': 'movimentação de grãos',
                'verbose_name_plural': 'movimentações de grãos',
                'ordering': ('-data_movimento', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='armazemgraos',
            constraint=models.UniqueConstraint(fields=('propriedade', 'nome'), name='graos_armazem_nome_propriedade_unico'),
        ),
        migrations.AddConstraint(
            model_name='armazemgraos',
            constraint=models.CheckConstraint(condition=models.Q(('capacidade_kg__gt', 0)), name='graos_armazem_capacidade_positiva'),
        ),
        migrations.AddIndex(
            model_name='lotegraos',
            index=models.Index(fields=['safra', 'cultura'], name='graos_lote_safra_cultura_idx'),
        ),
        migrations.AddConstraint(
            model_name='lotegraos',
            constraint=models.UniqueConstraint(fields=('armazem', 'codigo'), name='graos_lote_codigo_armazem_unico'),
        ),
        migrations.AddConstraint(
            model_name='lotegraos',
            constraint=models.CheckConstraint(condition=models.Q(('umidade_percentual__isnull', True), models.Q(('umidade_percentual__gte', 0), ('umidade_percentual__lte', 100)), _connector='OR'), name='graos_lote_umidade_valida'),
        ),
        migrations.AddConstraint(
            model_name='lotegraos',
            constraint=models.CheckConstraint(condition=models.Q(('impureza_percentual__isnull', True), models.Q(('impureza_percentual__gte', 0), ('impureza_percentual__lte', 100)), _connector='OR'), name='graos_lote_impureza_valida'),
        ),
        migrations.AddIndex(
            model_name='movimentacaograos',
            index=models.Index(fields=['lote', 'data_movimento'], name='graos_movimento_lote_data_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaograos',
            index=models.Index(fields=['referencia_externa'], name='graos_movimento_referencia_idx'),
        ),
        migrations.AddConstraint(
            model_name='movimentacaograos',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_kg__gt', 0)), name='graos_movimento_quantidade_positiva'),
        ),
    ]
