# Generated by Django 5.1.15 on 2026-08-10 01:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadpro', '0001_initial'),
        ('graos', '0004_saldos_constraints'),
        ('propriedades', '0003_propriedade_area_calculada_hectares_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoColheita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('cultura', models.CharField(max_length=50)),
                ('safra', models.CharField(max_length=20)),
                ('tolerancia_umidade_percentual', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('desconto_umidade_por_ponto', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('tolerancia_impureza_percentual', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('desconto_impureza_por_ponto', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('tolerancia_defeitos_percentual', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('desconto_defeitos_por_ponto', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cad_pro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos_colheita', to='cadpro.cadpro')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos_colheita_criados', to=settings.AUTH_USER_MODEL)),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos_colheita', to='propriedades.propriedade')),
            ],
            options={
                'verbose_name': 'grupo de colheita',
                'verbose_name_plural': 'grupos de colheita',
                'ordering': ('-safra', 'cultura', 'nome', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CargaColhida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_colheita', models.DateField(default=django.utils.timezone.localdate)),
                ('placa', models.CharField(max_length=7)),
                ('peso_bruto_kg', models.DecimalField(decimal_places=3, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('umidade_percentual', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('impureza_percentual', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('defeitos_percentual', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('ph', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('destinado_semente', models.BooleanField(default=False)),
                ('local_colheita', models.CharField(blank=True, max_length=160)),
                ('desconto_total_percentual', models.DecimalField(decimal_places=3, max_digits=7)),
                ('desconto_total_kg', models.DecimalField(decimal_places=3, max_digits=16)),
                ('peso_liquido_kg', models.DecimalField(decimal_places=3, max_digits=16)),
                ('sacas_60kg', models.DecimalField(decimal_places=3, max_digits=16)),
                ('regra_desconto_aplicada', models.JSONField(default=dict)),
                ('fingerprint', models.CharField(editable=False, max_length=64, unique=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('armazem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargas_colhidas', to='graos.armazemgraos')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargas_colhidas_criadas', to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargas_colhidas', to='graos.lotegraos')),
                ('movimentacao', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carga_colhida', to='graos.movimentacaograos')),
                ('grupo_colheita', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargas', to='graos.grupocolheita')),
            ],
            options={
                'verbose_name': 'carga colhida',
                'verbose_name_plural': 'cargas colhidas',
                'ordering': ('-data_colheita', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='grupocolheita',
            index=models.Index(fields=['propriedade', 'safra', 'cultura'], name='graos_grupo_prop_safra_idx'),
        ),
        migrations.AddConstraint(
            model_name='grupocolheita',
            constraint=models.UniqueConstraint(fields=('propriedade', 'cad_pro', 'nome', 'cultura', 'safra'), name='graos_grupo_colheita_unico'),
        ),
        migrations.AddIndex(
            model_name='cargacolhida',
            index=models.Index(fields=['grupo_colheita', 'data_colheita'], name='graos_carga_grupo_data_idx'),
        ),
        migrations.AddIndex(
            model_name='cargacolhida',
            index=models.Index(fields=['placa', 'data_colheita'], name='graos_carga_placa_data_idx'),
        ),
        migrations.AddConstraint(
            model_name='cargacolhida',
            constraint=models.CheckConstraint(condition=models.Q(('peso_bruto_kg__gt', 0)), name='graos_carga_peso_bruto_positivo'),
        ),
        migrations.AddConstraint(
            model_name='cargacolhida',
            constraint=models.CheckConstraint(condition=models.Q(('peso_liquido_kg__gt', 0)), name='graos_carga_peso_liquido_positivo'),
        ),
        migrations.AddConstraint(
            model_name='cargacolhida',
            constraint=models.CheckConstraint(condition=models.Q(('peso_liquido_kg__lte', models.F('peso_bruto_kg'))), name='graos_carga_liquido_ate_bruto'),
        ),
    ]
