# Generated by Django 5.1.15 on 2026-08-10 03:04

import django.db.models.deletion
from django.db import migrations, models


def preencher_armazem_padrao(apps, schema_editor):
    GrupoColheita = apps.get_model("graos", "GrupoColheita")
    ArmazemGraos = apps.get_model("graos", "ArmazemGraos")
    CargaColhida = apps.get_model("graos", "CargaColhida")
    for grupo in GrupoColheita.objects.filter(armazem_padrao__isnull=True):
        armazem_id = (
            CargaColhida.objects.filter(grupo_colheita_id=grupo.pk)
            .filter(armazem__ativo=True)
            .order_by("criado_em", "pk")
            .values_list("armazem_id", flat=True)
            .first()
        )
        if armazem_id is None:
            armazem_id = (
                ArmazemGraos.objects.filter(
                    propriedade_id=grupo.propriedade_id,
                    ativo=True,
                )
                .order_by("nome", "pk")
                .values_list("pk", flat=True)
                .first()
            )
        if armazem_id is not None:
            GrupoColheita.objects.filter(pk=grupo.pk).update(
                armazem_padrao_id=armazem_id
            )


class Migration(migrations.Migration):

    dependencies = [
        ('graos', '0005_grupocolheita_cargacolhida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupocolheita',
            name='armazem_padrao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grupos_colheita_padrao', to='graos.armazemgraos'),
        ),
        migrations.RunPython(preencher_armazem_padrao, migrations.RunPython.noop),
    ]
