# Generated by Django 5.1.15 on 2026-08-27 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graos', '0009_cargacolhida_contexto_direto_e_cancelamento'),
        ('propriedades', '0003_propriedade_area_calculada_hectares_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armazemgraos',
            name='propriedade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='armazens_graos', to='propriedades.propriedade'),
        ),
        migrations.AddConstraint(
            model_name='armazemgraos',
            constraint=models.UniqueConstraint(condition=models.Q(('propriedade__isnull', True)), fields=('nome',), name='graos_armazem_externo_nome_unico'),
        ),
    ]
