# Generated by Django 5.1.15 on 2026-08-27 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadpro', '0001_initial'),
        ('graos', '0010_alter_armazemgraos_propriedade_and_more'),
        ('propriedades', '0003_propriedade_area_calculada_hectares_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateioCargaColhida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_hectares', models.DecimalField(decimal_places=4, max_digits=14)),
                ('proporcao', models.DecimalField(decimal_places=9, max_digits=12)),
                ('peso_liquido_kg', models.DecimalField(decimal_places=3, max_digits=16)),
                ('sacas_60kg', models.DecimalField(decimal_places=3, max_digits=16)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cad_pro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rateios_cargas_colhidas', to='cadpro.cadpro')),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rateios', to='graos.cargacolhida')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rateios_cargas_colhidas', to='graos.lotegraos')),
                ('movimentacao', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='rateio_carga_colhida', to='graos.movimentacaograos')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rateios_cargas_colhidas', to='propriedades.propriedade')),
            ],
            options={
                'verbose_name': 'rateio de carga colhida',
                'verbose_name_plural': 'rateios de cargas colhidas',
                'ordering': ('carga_id', 'propriedade_id'),
                'constraints': [models.UniqueConstraint(fields=('carga', 'propriedade'), name='graos_rateio_carga_propriedade_unico'), models.CheckConstraint(condition=models.Q(('area_hectares__gt', 0)), name='graos_rateio_area_positiva'), models.CheckConstraint(condition=models.Q(('proporcao__gt', 0), ('proporcao__lte', 1)), name='graos_rateio_proporcao_valida'), models.CheckConstraint(condition=models.Q(('peso_liquido_kg__gt', 0)), name='graos_rateio_peso_positivo')],
            },
        ),
    ]
