# Generated by Django 5.1.15 on 2026-08-29 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadpro', '0001_initial'),
        ('graos', '0011_rateiocargacolhida'),
        ('propriedades', '0003_propriedade_area_calculada_hectares_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='posicaosaldograos',
            name='graos_posicao_chave_unica',
        ),
        migrations.AddField(
            model_name='lotegraos',
            name='propriedade',
            field=models.ForeignKey(blank=True, help_text='Propriedade produtora; independe da armazenagem física.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes_graos', to='propriedades.propriedade'),
        ),
        migrations.AddField(
            model_name='posicaosaldograos',
            name='propriedade',
            field=models.ForeignKey(blank=True, help_text='Propriedade produtora; independe da armazenagem física.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posicoes_saldo_graos', to='propriedades.propriedade'),
        ),
        migrations.AddIndex(
            model_name='posicaosaldograos',
            index=models.Index(fields=['propriedade', 'cad_pro', 'cultura', 'safra'], name='graos_posicao_prop_cad_idx'),
        ),
        migrations.AddConstraint(
            model_name='posicaosaldograos',
            constraint=models.UniqueConstraint(fields=('propriedade', 'cad_pro', 'cultura', 'safra', 'classificacao_codigo', 'armazem'), name='graos_posicao_prop_chave_unica'),
        ),
    ]
