# Generated by Django 5.1.15 on 2026-08-30 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graos', '0012_propriedade_producao_saldos'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='posicaosaldograos',
            name='graos_posicao_fisico_nao_negativo',
        ),
        migrations.RemoveConstraint(
            model_name='posicaosaldograos',
            name='graos_posicao_comprom_ate_fisico',
        ),
    ]
