# Generated by Django 5.1.15 on 2026-10-02 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graos', '0013_permitir_saldo_negativo_vendas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrecaoTransferenciaSaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('editar', 'Editar'), ('excluir', 'Excluir')], max_length=8)),
                ('motivo', models.CharField(max_length=500)),
                ('chave_idempotencia', models.CharField(max_length=160, unique=True)),
                ('hash_requisicao', models.CharField(max_length=64)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('origem_nova', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correcao_anterior', to='graos.origemsaldograos')),
                ('origem_original', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='correcao_transferencia', to='graos.origemsaldograos')),
            ],
            options={
                'verbose_name': 'correção de transferência de saldo',
                'ordering': ('-criado_em', '-id'),
            },
        ),
    ]
