# Generated by Django 5.1.15 on 2026-10-05 11:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graos', '0014_correcaotransferenciasaldo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaProducaoTerceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depositante', models.CharField(max_length=160)),
                ('propriedade_origem', models.CharField(blank=True, max_length=160)),
                ('cad_pro', models.CharField(blank=True, max_length=80)),
                ('cultura', models.CharField(max_length=50)),
                ('safra', models.CharField(max_length=20)),
                ('peso_liquido_kg', models.DecimalField(decimal_places=3, max_digits=16)),
                ('saldo_kg', models.DecimalField(decimal_places=3, max_digits=16)),
                ('data_entrada', models.DateField(default=django.utils.timezone.localdate)),
                ('placa', models.CharField(blank=True, max_length=7)),
                ('motorista', models.CharField(blank=True, max_length=120)),
                ('documento', models.CharField(blank=True, max_length=120)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('armazem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='graos.armazemgraos')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-data_entrada', '-id'),
            },
        ),
        migrations.CreateModel(
            name='MovimentoProducaoTerceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('estorno', 'Estorno')], max_length=8)),
                ('quantidade_kg', models.DecimalField(decimal_places=3, max_digits=16)),
                ('delta_kg', models.DecimalField(decimal_places=3, max_digits=16)),
                ('saldo_anterior_kg', models.DecimalField(decimal_places=3, max_digits=16)),
                ('saldo_posterior_kg', models.DecimalField(decimal_places=3, max_digits=16)),
                ('data_movimento', models.DateField(default=django.utils.timezone.localdate)),
                ('destino', models.CharField(blank=True, max_length=160)),
                ('documento', models.CharField(blank=True, max_length=120)),
                ('placa', models.CharField(blank=True, max_length=7)),
                ('motorista', models.CharField(blank=True, max_length=120)),
                ('observacoes', models.TextField(blank=True)),
                ('chave_idempotencia', models.CharField(max_length=160, unique=True)),
                ('hash_requisicao', models.CharField(max_length=64)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='graos.entradaproducaoterceiro')),
                ('estorno_de', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estorno', to='graos.movimentoproducaoterceiro')),
            ],
            options={
                'ordering': ('-criado_em', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='entradaproducaoterceiro',
            constraint=models.CheckConstraint(condition=models.Q(('peso_liquido_kg__gt', 0)), name='terceiro_entrada_peso_positivo'),
        ),
        migrations.AddConstraint(
            model_name='entradaproducaoterceiro',
            constraint=models.CheckConstraint(condition=models.Q(('saldo_kg__gte', 0), ('saldo_kg__lte', models.F('peso_liquido_kg'))), name='terceiro_entrada_saldo_valido'),
        ),
        migrations.AddConstraint(
            model_name='movimentoproducaoterceiro',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_kg__gt', 0)), name='terceiro_mov_peso_positivo'),
        ),
    ]
