# Generated by Django 5.1.15 on 2026-10-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graos', '0015_producao_terceiros'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaproducaoterceiro',
            name='defeitos_percentual',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='entradaproducaoterceiro',
            name='desconto_total_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='entradaproducaoterceiro',
            name='desconto_total_percentual',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='entradaproducaoterceiro',
            name='impureza_percentual',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='entradaproducaoterceiro',
            name='peso_bruto_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='entradaproducaoterceiro',
            name='ph',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='entradaproducaoterceiro',
            name='regra_desconto_aplicada',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='entradaproducaoterceiro',
            name='umidade_percentual',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True),
        ),
    ]
