# Generated by Django 5.1.15 on 2026-10-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graos', '0016_entradaproducaoterceiro_defeitos_percentual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaproducaoterceiro',
            name='versao',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='movimentoproducaoterceiro',
            name='snapshot_antes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='movimentoproducaoterceiro',
            name='snapshot_depois',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='movimentoproducaoterceiro',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('estorno', 'Estorno'), ('edicao', 'Edição')], max_length=8),
        ),
    ]
