# Generated by Django 5.1.15 on 2026-10-06 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graos', '0017_entradaproducaoterceiro_versao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentoproducaoterceiro',
            name='movimentacao_saldo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimento_terceiro', to='graos.movimentacaograos'),
        ),
        migrations.AlterField(
            model_name='movimentoproducaoterceiro',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('estorno', 'Estorno'), ('edicao', 'Edição'), ('transferencia', 'Transferência para CAD/PRO')], max_length=13),
        ),
    ]
