# Generated by Django 5.1.15 on 2026-10-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graos', '0018_transferencia_terceiros'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargacolhida',
            name='peso_total_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='cargacolhida',
            name='tara_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='entradaproducaoterceiro',
            name='peso_total_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='entradaproducaoterceiro',
            name='tara_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True),
        ),
    ]
