# Generated by Django 5.1.15 on 2026-10-07 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graos', '0019_cargacolhida_peso_total_kg_cargacolhida_tara_kg_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenciaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultura', models.CharField(max_length=50)),
                ('safra', models.CharField(max_length=20)),
                ('data_contagem', models.DateField()),
                ('contado_kg', models.DecimalField(decimal_places=3, max_digits=16)),
                ('saldo_proprio_kg', models.DecimalField(decimal_places=3, max_digits=16)),
                ('saldo_terceiros_kg', models.DecimalField(decimal_places=3, max_digits=16)),
                ('justificativa', models.TextField()),
                ('chave_idempotencia', models.UUIDField(unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('armazem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='graos.armazemgraos')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('contado_kg__gte', 0)), name='conferencia_estoque_contagem_positiva')],
            },
        ),
    ]
