# Generated by Django 5.1.15 on 2026-10-07 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graos', '0020_conferenciaestoque'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TerceiroCadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('nome', models.CharField(max_length=160)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('nome', 'id'),
            },
        ),
        migrations.CreateModel(
            name='FechamentoPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultura', models.CharField(max_length=50)),
                ('safra', models.CharField(max_length=20)),
                ('inicio', models.DateField()),
                ('fim', models.DateField()),
                ('saldo_proprio_kg', models.DecimalField(decimal_places=3, max_digits=16)),
                ('saldo_terceiros_kg', models.DecimalField(decimal_places=3, max_digits=16)),
                ('assinatura', models.CharField(max_length=64)),
                ('justificativa', models.TextField()),
                ('chave_idempotencia', models.UUIDField(unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('armazem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='graos.armazemgraos')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PendenciaConferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('detalhes', models.JSONField(default=dict)),
                ('situacao', models.CharField(choices=[('aberta', 'Aberta'), ('em_analise', 'Em análise'), ('resolvida', 'Resolvida')], default='aberta', max_length=12)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='entradaproducaoterceiro',
            name='terceiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='graos.terceirocadastro'),
        ),
    ]
