# Generated by Django 5.1.15 on 2026-07-26 02:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoticiaMercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=220)),
                ('resumo', models.TextField(blank=True)),
                ('fonte', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=500)),
                ('publicada_em', models.DateTimeField()),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-publicada_em', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ClimaCornBelt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regiao', models.CharField(choices=[('iowa', 'Iowa'), ('illinois', 'Illinois'), ('indiana', 'Indiana'), ('nebraska', 'Nebraska'), ('minnesota', 'Minnesota')], max_length=20)),
                ('data', models.DateField()),
                ('temperatura_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperatura_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precipitacao_mm', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('alerta', models.CharField(blank=True, max_length=160)),
                ('fonte', models.CharField(default='Open-Meteo', max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('regiao', 'data'),
                'constraints': [models.UniqueConstraint(fields=('regiao', 'data'), name='mercado_corn_belt_unico_regiao_data'), models.CheckConstraint(condition=models.Q(('precipitacao_mm__gte', 0)), name='mercado_corn_belt_chuva_nao_negativa')],
            },
        ),
        migrations.CreateModel(
            name='CotacaoMercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(choices=[('soja', 'Soja'), ('milho', 'Milho'), ('trigo', 'Trigo'), ('brent', 'Petróleo Brent')], max_length=20)),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('unidade', models.CharField(max_length=50)),
                ('fonte', models.CharField(default='FRED / FMI', max_length=80)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('produto', 'data'),
                'indexes': [models.Index(fields=['produto', '-data'], name='mercado_prod_data_idx')],
                'constraints': [models.UniqueConstraint(fields=('produto', 'data'), name='mercado_cotacao_unica_produto_data'), models.CheckConstraint(condition=models.Q(('valor__gte', 0)), name='mercado_cotacao_valor_nao_negativo')],
            },
        ),
    ]
