# Generated by Django 5.1.15 on 2026-07-30 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('graos', '0001_initial'),
        ('propriedades', '0003_propriedade_area_calculada_hectares_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteImportacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_nome', models.CharField(max_length=255)),
                ('arquivo_tamanho', models.PositiveBigIntegerField()),
                ('arquivo_sha256', models.CharField(editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('concluido', 'Concluído'), ('com_erros', 'Concluído com erros')], editable=False, max_length=20)),
                ('total_planilhas', models.PositiveIntegerField(default=0, editable=False)),
                ('total_linhas', models.PositiveIntegerField(default=0, editable=False)),
                ('total_validas', models.PositiveIntegerField(default=0, editable=False)),
                ('total_advertencias', models.PositiveIntegerField(default=0, editable=False)),
                ('total_erros', models.PositiveIntegerField(default=0, editable=False)),
                ('metadados', models.JSONField(blank=True, default=dict, editable=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_importacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'lote de importação',
                'verbose_name_plural': 'lotes de importação',
                'ordering': ('-criado_em', '-id'),
            },
        ),
        migrations.CreateModel(
            name='LinhaImportacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequencia', models.PositiveIntegerField()),
                ('planilha', models.CharField(max_length=100)),
                ('linha_origem', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('producao', 'Produção'), ('saida', 'Saída'), ('terceiros', 'Recebimento de terceiros')], max_length=15)),
                ('status', models.CharField(choices=[('valida', 'Válida'), ('advertencia', 'Com advertência'), ('erro', 'Com erro')], editable=False, max_length=15)),
                ('hash_linha', models.CharField(db_index=True, editable=False, max_length=64)),
                ('dados_originais', models.JSONField(default=dict, editable=False)),
                ('dados_normalizados', models.JSONField(default=dict, editable=False)),
                ('erros', models.JSONField(blank=True, default=list, editable=False)),
                ('advertencias', models.JSONField(blank=True, default=list, editable=False)),
                ('associacao', models.CharField(choices=[('nao_associada', 'Não associada'), ('propriedade', 'Propriedade associada'), ('lote_graos', 'Lote de grãos associado')], default='nao_associada', editable=False, max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('lote_graos', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linhas_importacao', to='graos.lotegraos')),
                ('propriedade', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linhas_importacao', to='propriedades.propriedade')),
                ('lote_importacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linhas', to='importacoes.loteimportacao')),
            ],
            options={
                'verbose_name': 'linha de importação',
                'verbose_name_plural': 'linhas de importação',
                'ordering': ('sequencia', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='loteimportacao',
            index=models.Index(fields=['status', 'criado_em'], name='importacao_status_data_idx'),
        ),
        migrations.AddIndex(
            model_name='linhaimportacao',
            index=models.Index(fields=['lote_importacao', 'status'], name='importacao_lote_status_idx'),
        ),
        migrations.AddIndex(
            model_name='linhaimportacao',
            index=models.Index(fields=['lote_importacao', 'tipo'], name='importacao_lote_tipo_idx'),
        ),
        migrations.AddConstraint(
            model_name='linhaimportacao',
            constraint=models.UniqueConstraint(fields=('lote_importacao', 'planilha', 'linha_origem'), name='importacao_lote_planilha_linha_unica'),
        ),
    ]
