# Generated by Django 5.1.15 on 2026-07-31 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graos', '0001_initial'),
        ('importacoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loteimportacao',
            options={'ordering': ('-criado_em', '-id'), 'permissions': [('confirmar_loteimportacao', 'Pode confirmar definitivamente lotes de importação')], 'verbose_name': 'lote de importação', 'verbose_name_plural': 'lotes de importação'},
        ),
        migrations.AddField(
            model_name='linhaimportacao',
            name='movimentacao_graos',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linha_importacao', to='graos.movimentacaograos'),
        ),
        migrations.AddField(
            model_name='loteimportacao',
            name='confirmado_em',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='loteimportacao',
            name='confirmado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes_importacao_confirmados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loteimportacao',
            name='status',
            field=models.CharField(choices=[('concluido', 'Concluído'), ('com_erros', 'Concluído com erros'), ('pronto_confirmacao', 'Pronto para confirmação'), ('confirmando', 'Confirmando'), ('confirmado', 'Confirmado'), ('falhou', 'Falhou')], editable=False, max_length=20),
        ),
        migrations.CreateModel(
            name='ConfirmacaoImportacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('confirmada', 'Confirmada'), ('falhou', 'Falhou')], editable=False, max_length=10)),
                ('resultado', models.JSONField(blank=True, default=dict, editable=False)),
                ('falha', models.TextField(blank=True, editable=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('lote_importacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tentativas_confirmacao', to='importacoes.loteimportacao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmacoes_importacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'confirmação de importação',
                'verbose_name_plural': 'confirmações de importação',
                'ordering': ('-criado_em', '-id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'confirmada')), fields=('lote_importacao',), name='importacao_lote_confirmacao_unica')],
            },
        ),
    ]
