# Generated by Django 5.1.15 on 2026-09-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graos', '0013_permitir_saldo_negativo_vendas'),
        ('importacoes', '0002_alter_loteimportacao_options_and_more'),
        ('propriedades', '0003_propriedade_area_calculada_hectares_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='linhaimportacao',
            constraint=models.UniqueConstraint(condition=models.Q(('movimentacao_graos__isnull', False)), fields=('hash_linha',), name='importacao_hash_confirmado_unico'),
        ),
    ]
