# Generated by Django 5.1.15 on 2026-07-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talhoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talhao',
            name='altitude_media',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='talhao',
            name='arquivo_kml',
            field=models.FileField(blank=True, null=True, upload_to='talhoes/kml/'),
        ),
        migrations.AddField(
            model_name='talhao',
            name='declividade_media',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='talhao',
            name='latitude_centro',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='talhao',
            name='longitude_centro',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='talhao',
            name='tipo_solo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
