# Generated by Django 5.1.15 on 2026-07-25 21:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propriedades', '0002_propriedade_arquivo_kml_propriedade_proprietario_and_more'),
        ('talhoes', '0004_alter_talhao_propriedade'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoAgronomico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_referencia', models.DateField()),
                ('cultura', models.CharField(blank=True, max_length=50)),
                ('safra', models.CharField(blank=True, max_length=20)),
                ('produtividade_esperada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('produtividade_realizada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'histórico agronômico',
                'verbose_name_plural': 'históricos agronômicos',
                'ordering': ('-data_referencia', '-id'),
            },
        ),
        migrations.AddField(
            model_name='talhao',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='talhao',
            name='produtividade_realizada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='talhao',
            name='produtividade_esperada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddConstraint(
            model_name='talhao',
            constraint=models.CheckConstraint(condition=models.Q(('produtividade_esperada__gte', 0), ('produtividade_esperada__isnull', True), _connector='OR'), name='talhao_produtividade_esperada_nao_negativa'),
        ),
        migrations.AddConstraint(
            model_name='talhao',
            constraint=models.CheckConstraint(condition=models.Q(('produtividade_realizada__gte', 0), ('produtividade_realizada__isnull', True), _connector='OR'), name='talhao_produtividade_realizada_nao_negativa'),
        ),
        migrations.AddField(
            model_name='historicoagronomico',
            name='talhao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos_agronomicos', to='talhoes.talhao'),
        ),
        migrations.AddConstraint(
            model_name='historicoagronomico',
            constraint=models.CheckConstraint(condition=models.Q(('produtividade_esperada__gte', 0), ('produtividade_esperada__isnull', True), _connector='OR'), name='historico_produtividade_esperada_nao_negativa'),
        ),
        migrations.AddConstraint(
            model_name='historicoagronomico',
            constraint=models.CheckConstraint(condition=models.Q(('produtividade_realizada__gte', 0), ('produtividade_realizada__isnull', True), _connector='OR'), name='historico_produtividade_realizada_nao_negativa'),
        ),
    ]
