# Generated by Django 5.1.15 on 2026-07-25 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talhoes', '0005_historicoagronomico_talhao_atualizado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoagronomico',
            name='talhao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historicos_agronomicos', to='talhoes.talhao'),
        ),
    ]
