# Generated by Django 5.1.15 on 2026-07-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talhoes', '0006_alter_historicoagronomico_talhao'),
    ]

    operations = [
        migrations.AddField(
            model_name='talhao',
            name='area_calculada_hectares',
            field=models.DecimalField(blank=True, decimal_places=4, editable=False, max_digits=14, null=True),
        ),
    ]
