# Generated by Django 5.1.15 on 2026-08-30 17:05

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_entregavendagraos_dados_saida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucaovendagraos',
            name='cancelado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entregavendagraos',
            name='cancelado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendagraos',
            name='excluida_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendagraos',
            name='versao',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='vendagraos',
            name='numero_contrato',
            field=models.CharField(max_length=80),
        ),
        migrations.CreateModel(
            name='AlteracaoVendaGraos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=40)),
                ('chave', models.CharField(max_length=120, unique=True)),
                ('hash_requisicao', models.CharField(max_length=64)),
                ('motivo', models.CharField(max_length=500)),
                ('antes', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('depois', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alteracoes', to='vendas.vendagraos')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ContratoComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=80)),
                ('empresa', models.CharField(max_length=160)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('empresa', 'numero', 'id'),
                'constraints': [models.UniqueConstraint(fields=('numero', 'empresa'), name='vendas_contrato_empresa_unico')],
            },
        ),
        migrations.AddField(
            model_name='vendagraos',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='vendas.contratocomercial'),
        ),
    ]
