# Generated by Django 5.1.15 on 2026-08-30 17:18

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_cadastrar_contratos_existentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratocomercial',
            name='produto',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='contratocomercial',
            name='quantidade_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
    ]
