# Generated by Django 5.1.15 on 2026-08-30 17:50

from django.db import migrations, models


def adicionar_motorista(apps, schema_editor):
    entrega = apps.get_model("vendas", "EntregaVendaGraos")
    tabela = entrega._meta.db_table
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        colunas = connection.introspection.get_table_description(cursor, tabela)
    if not any(c.name == "motorista" for c in colunas):
        # Default no banco permite que versões anteriores insiram entregas
        # sem conhecer a coluna, que é preservada durante rollback.
        campo = models.CharField(blank=True, max_length=160, db_default="")
        campo.set_attributes_from_name("motorista")
        campo.model = entrega
        schema_editor.add_field(entrega, campo)
        return
    # O banco local já possuía varchar(120), sem registro desta migration.
    # Validar a estrutura e somente ampliar; nunca apagar ou truncar nomes.
    if connection.vendor == "sqlite":
        coluna = next(c for c in colunas if c.name == "motorista")
        if str(coluna.type_code).lower() == "varchar(160)" and not coluna.null_ok:
            return
        raise RuntimeError("Coluna motorista SQLite incompatível; nenhum dado foi alterado.")
    if connection.vendor != "postgresql":
        raise RuntimeError("Coluna motorista preexistente: revisar compatibilidade antes de migrar.")
    with connection.cursor() as cursor:
        cursor.execute("SELECT data_type, character_maximum_length, is_nullable FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = %s AND column_name = %s", [tabela, "motorista"])
        tipo, tamanho, nullable = cursor.fetchone()
    if tipo != "character varying" or tamanho not in (120, 160) or nullable != "NO":
        raise RuntimeError("Estrutura inesperada de motorista; nenhum dado foi alterado.")
    if tamanho == 120:
        schema_editor.execute(f"ALTER TABLE {schema_editor.quote_name(tabela)} ALTER COLUMN motorista TYPE varchar(160)")


def preservar_motorista_no_retorno(apps, schema_editor):
    # Não remover uma coluna que já podia existir antes desta migration.
    # PostgreSQL legado pode não ter default; manter inserts antigos válidos.
    if schema_editor.connection.vendor == "postgresql":
        tabela = apps.get_model("vendas", "EntregaVendaGraos")._meta.db_table
        schema_editor.execute(f"ALTER TABLE {schema_editor.quote_name(tabela)} ALTER COLUMN motorista SET DEFAULT ''")


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_contratocomercial_produto_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(database_operations=[migrations.RunPython(adicionar_motorista, preservar_motorista_no_retorno)], state_operations=[migrations.AddField(
            model_name='entregavendagraos',
            name='motorista',
            field=models.CharField(blank=True, max_length=160),
        )]),
    ]
