# Generated by Django 5.1.15 on 2026-10-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0008_rateio_venda_particular'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregavendagraos',
            name='avariados_percentual',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='entregavendagraos',
            name='peso_bruto_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='entregavendagraos',
            name='ph',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='entregavendagraos',
            name='quebrados_percentual',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='entregavendagraos',
            name='tara_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='entregavendagraos',
            name='umidade_percentual',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True),
        ),
    ]
